### ISSUE TITLE
oflaDemo rtmp link not working

### ISSUE THREAD

**Issue by ajvanho6** [Red5/red5-server#102]
Hi having problem with oflaDemo..having message No scope 'oflaDemo' on this server. I try editing red5-web.properties virtual hosts puting my webadress insted of localhost..... localhost, localhost:8088, 127.0.0.1:8088 but no luck. Cant make oflaDemo rtmp stream to work. Any tips. Ubuntu vps server.

**Comment by mondain** [comment]
Did you install oflaDemo? Is there an oflaDemo directory in your red5 install? /red5/webapps/oflaDemo
