### ISSUE TITLE
red5 integration with kaltura on streaming

### ISSUE THREAD

**Issue by noamtahan** [Red5/red5-server#105]
Hi,
I am using red5 with the oflademo example to play streaming video.
I understand that if I want to use streaming deliver kaltura integrate with red5 server its not working.
I tried to figure out why, but they have no any idea.
Until today, all the kaltura users use kaltura with wowza streaming server for streaming delivery , just because the error with the integration between red5 kaltura.
Can some one from the red5 community help us to solve this issue?
Thanks in advanced.
p.s.
the live streaming is working.

links:

[can't preview & embed rtmp streaming!](https://github.com/kaltura/platform-install-packages/issues/140)
[RTMP issue No Media Found!](http://forum.kaltura.org/t/clip-not-found-media-not-found-on-rtmp-streaming-kaltura-9-16-0/254/8)
[RTMP](http://forum.kaltura.org/t/rtmp-issue-no-media-found-jupiter-10-7-0/2068)
[MORE](http://forum.kaltura.org/search?q=red5%20streaming)

**Comment by mondain** [comment]
This is a Kaltura issue not a Red5; it is up to them to fix it unless otherwise shown that it is our server.
