### ISSUE TITLE
Facing this while running ant server

### ISSUE THREAD

**Issue by antoniomerlin** [Red5/red5-server#106]
Facing this while running ant server
`C:\Program Files\Red5\build.xml:183: impossible to resolve dependencies: java.lang.IllegalArgumentException: requested configuration not found in red5#server;working@OJICTDML01: [ 'java5' ]`

ant version : 1.7.1
java version : 1.8
ivy version : 2.4.0

how to resolve this one can you help me

**Comment by solomax** [comment]
red5-server should be built with Maven, not Ant

**Comment by antoniomerlin** [comment]
could you brief me

**Comment by mondain** [comment]
Install maven and then take a look at the wiki entry https://github.com/Red5/red5-server/wiki/Maven
