### ISSUE TITLE
Please new tutorials for red5 client application create & run

### ISSUE THREAD

**Issue by ismersoy** [Red5/red5-server#108]
Hi
I'm new on red5 server and java, i build and run red5 on eclipse using maven, but I can not run a new client app using red5plugin or other techniques.

I'm asking you a new tutorial for create and run red5 client app (use latest version applications)

Red5 1.0.5 Release (https://github.com/Red5/red5-server/releases/download/v1.0.5-RELEASE/red5-server-1.0.5-RELEASE-server.zip)
Eclipse (Mars)
Eclipse Red5 Plugin and/or other techniques
Java Version 8 (or which?)
Adobe Flash

Thank you for your help and sorry for my english.

**Comment by dizag** [comment]
if somebody succeed to build and run last red5-server-1.0.7-SNAPSHOT please help :)

generated files 
red5-server-1.0.7-SNAPSHOT.jar
red5-server-1.0.7-SNAPSHOT.pom
red5-server-1.0.7-SNAPSHOT-sources.jar
red5-server-1.0.7-SNAPSHOT-javadoc.jar

have to be renamed and moved in target directory or what ? 
how to deal with this bootstrap - did i have to compile from red5-service and again rename and move in target directory ...

if somebody succeed to build and run last red5-server-1.0.7-SNAPSHOT please help :)

**Comment by solomax** [comment]
As stated in https://github.com/Red5/red5-server/blob/master/README.md you need to run `mvn -Dmaven.test.skip=true clean package -P assemble` to create server bundle

NOTE according to this: https://groups.google.com/forum/#!topic/red5interest/RSlChIgXgF8 current HEAD is a little bit broken, work is in progress

**Comment by dizag** [comment]
thank you solomax,
i'll keep trying :)

**Comment by mondain** [comment]
Yes, please use the assemble profile to build the (assembly) tar.gz/zip of the server.
