### ISSUE TITLE
I can't connect to the http://red5.googlecode.com/svn/snapshots/ and give me another address. Thank you

### ISSUE THREAD

**Issue by yangcuiwang** [Red5/red5-server#109]
I can't connect to the http://red5.googlecode.com/svn/snapshots/ and give me another address. Thank you

**Comment by AlejandroMoran** [comment]
https://builds.apache.org/view/M-R/view/OpenMeetings/job/Red5-server/
or this one for windows installer
https://builds.apache.org/view/M-R/view/OpenMeetings/job/red5-installer/

**Comment by mondain** [comment]
Everything is on github now, google shut the other site down.

**Comment by zdanek** [comment]
Come on! This address  http://red5.googlecode.com/svn/snapshots/  is used also by red5 demo app installer. There's no demo apps because the address does not exist any more.
What is new address?

**Comment by mondain** [comment]
https://github.com/Red5/red5-server/issues/180
