### ISSUE TITLE
getting rejected message when trying to update the  shared object continuously

### ISSUE THREAD

**Issue by red5user** [Red5/red5-server#110]
I'm getting the following info when trying to update the shared object continuously

 [INFO] [NioProcessor-10] org.red5.server.net.rtmp.RTMPConnection - Rejected message: Packet [[header data type=17, channel=3, timer=611890], [message timestamp=611890]] on WKA5HIUZ0KEJJ

**Comment by mondain** [comment]
Is the SO locked when you attempt to access it? If you are updating it too frequently or it is not completing quick enough I would think you should expect to see this message. Either way, you'll need a lot more detail in your issue report than what is provided.

**Comment by mondain** [comment]
I just worked on this issue with another dev and we increased this value in <i>red5/conf/red5.properties</i>
```
so.max.events.per.update=64
```
From a default of 64 to 120 and the issue went away; give it go and let us know.
