### ISSUE TITLE
HEEEEELLLPPP.

### ISSUE THREAD

**Issue by Adamngooddad** [Red5/red5-server#111]
Need help with RED 5 admin. It is not accepting my Credentials at all. ALSO cannot pull page where I can apply for a new admin . NEED HELP/

**Comment by mondain** [comment]
I believe Deepak on the users list has a more robust and functional admin console; I suggest using that since it may be awhile before we modify the demo admin app.

**Comment by Adamngooddad** [comment]
Excellent, I really appreciate the help, BUT What is DEEPAK, HOW and WHERE DO I GET?

**Comment by mondain** [comment]
Join the users list or just search it https://groups.google.com/forum/#!forum/red5interest
