### ISSUE TITLE
Install WAR through installer web-interface

### ISSUE THREAD

**Issue by smarek** [Red5/red5-server#115]
Hello,

is it possible to deploy WAR plugin through `host:5080/installer/installer.swf` interface?
Or another part of web-interface administration?

Thank you!

**Comment by mondain** [comment]
Drop your war into the webapps directory and the deployer will load it. As for doing it manually, you'd have to look over the source to see where you'd want to hook in.

**Comment by mondain** [comment]
I suggest any further queries be posted to the users list, this section of the site is for "issues" / "bugs".
