### ISSUE TITLE
Red5 with WebRTC support?

### ISSUE THREAD

**Issue by rinodung** [Red5/red5-server#118]
Does Red5 support with WebRTC in the future? And how I connect to red5 without using Flash technology?

**Comment by mondain** [comment]
Today, you cannot connect to red5 using a peer connection, unless you write that part yourself; In the future we hope to support WebRTC.

**Comment by mseddon** [comment]
I'm curious as to if this will change soon given the launch of the Red5 Pro WebRTC beta?

**Comment by mondain** [comment]
WebRTC is implemented by Red5 Pro, on top of Red5. Red5 itself does not have all the required parts to provide WebRTC itself.

**Comment by mseddon** [comment]
Fair enough, thanks for the info!

**Comment by muzammil360** [comment]
Hi @mondain, this seems like a 4 years old thread but I have the same question. Does Red5 support webrtc now?

**Comment by mondain** [comment]
It doesn't, no.

**Comment by Trolldemorted** [comment]
Any chance this is going to change in the future?
