### ISSUE TITLE
SLF4J Multiple Binding

### ISSUE THREAD

**Issue by mayras** [Red5/red5-server#120]
Logs always has next rows: 
SLF4J: Found binding in [jar:file:/C:/Work/Projects/****/Temp/red5-rtsp-restreamer/target/rtsp-restreamer-1.0/WEB-INF/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Work/Projects/*****/Temp/red5-rtsp-restreamer/target/rtsp-restreamer-1.0/WEB-INF/lib/red5-server-1.0.6-RELEASE.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J Binding should be specified by developer, but not included inside red5-server

**Comment by mondain** [comment]
We implement our own static binder and are well aware of this message. The "developer" is free to do whatever they like as they have full access to the source.

**Comment by mayras** [comment]
The problem is that developers need to exclude your static binder from source code to have own one, it's not flexible to choose necessary logger for SLF4J. May be it should be done as separated module or using some delegation to make life easier for customization.

According to code: you need getContextSelector() from your StaticLoggerBinder
Another solution: you can access this method by call ContextSelectorStaticBinder.getSingleton().getContextSelector() without implementation of own static binder directly, same way done as done in class ch.qos.logback.classic.selector.servlet.LoggerContextFilter

**Comment by mondain** [comment]
I'm fairly certain the way you does not work; in addition you can change the loggers via vm parameter.
