### ISSUE TITLE
org.red5.server.net.rtmp.RTMPMinaTransport.start()/stop() uses ThreadPoolExecutor incorrectly (lines 135, 140)

### ISSUE THREAD

**Issue by mayras** [Red5/red5-server#121]
org.red5.server.net.rtmp.RTMPMinaTransport has to dispose field 'acceptor' in method stop() to release executors which are assined in org.red5.server.net.rtmp.RTMPMinaTransport.start().

**Comment by mondain** [comment]
You would propose which solution for this implied issue?

**Comment by mayras** [comment]
just need to call acceptor.dispose() and make checking field 'enableDefaultAcceptor', if it's false, then make shutfown() for internal 'executor' which is created in RTMPMinaTransport:

			// simple pool for i/o processors
			SimpleIoProcessorPool<NioSession> pool = new SimpleIoProcessorPool<NioSession>(NioProcessor.class, maxProcessorPoolSize);
			// executor for acceptors, defaults to 32k for work queue
			Executor executor = new ThreadPoolExecutor(initialPoolSize, maxPoolSize, executorKeepAliveTime, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(Short.MAX_VALUE));

**Comment by mondain** [comment]
Fix / adjustment to stop is now in the repo
