### ISSUE TITLE
Red5 streaming with authentication

### ISSUE THREAD

**Issue by pol2095** [Red5/red5-server#122]
Hello,

Red5 has a built-in webapp called live, but it doesn’t use authentication. Everyone will be able to publish and watch streams using your private Red5 server.

is-it possible to use authentication ?

Thanks

**Comment by mondain** [comment]
Yes, authentication is possible in pretty much any way you can implement. Here's an example: http://blog.infrared5.com/2012/05/red5-authentication/
Lastly, please "ask" questions on the users list, this is the place to post "issues".
