### ISSUE TITLE
Live Audio Streaming Delay

### ISSUE THREAD

**Issue by winneryong** [Red5/red5-server#127]
Hi
In 10 client only live audio chat, but encounter random client audio delay, delay time 7,8 seconds.
client swf set NetStream's bufferTime = 0 and server set rtmp.send_buffer_size=200
rtmp.receive_buffer_size=200 not resolve this problem, have other solution? thanks.

**Comment by winneryong** [comment]
when a client multi-times close stream and open stream (publish and play) encounter  this issue.

**Comment by mondain** [comment]
This report needs more information as to how this occurs and also most importantly, which version of Red5 you are using.

**Comment by winneryong** [comment]
i found reason, when client using microphone default  codec(NELLYMOSER)  encounter this problem, change to speex codec not appear delay problem, but voice quality very bad。
i use red5 1.0
operation list below:
UserA And UserB connect red5 sever,  now both client no delay.
UserA Client close and connect red5 server four times, the UserB listen UseA's voice delay. 
UserB reconnect to red5 server delay disappear.

both client not publish and play video. voice only.

**Comment by mondain** [comment]
Speex is a better choice when doing voice only; that being said there are a lot of options for Speex on the client-side and I would suggest adjusting them until you find what works best for your app. I would also suggest that you not modify the RTMP buffer sizes from the defaults in red5.properties.

**Comment by winneryong** [comment]
ok, Thank you for your advice.
