### ISSUE TITLE
how to Customize Stream Path

### ISSUE THREAD

**Issue by chushiyun2015** [Red5/red5-server#129]
https://github.com/Red5/red5-server/wiki/Customize-Stream-Path
I customize a path equals "d:\streams",then run oflaDemo，but can't playback the video. Is there any issue?
package org.red5.demos.oflaDemo;

import org.red5.logging.Red5LoggerFactory;
import org.red5.server.api.scope.IScope;
import org.red5.server.api.stream.IStreamFilenameGenerator;

public class CustomerFilenameGenerator implements IStreamFilenameGenerator {
    private static org.slf4j.Logger log = Red5LoggerFactory.getLogger(CustomerFilenameGenerator.class, "oflaDemo");
    private String recordPath = "recordedStreams/";
    //private String playbackPath = "videoStreams/";
    private String playbackPath = "D:\\streams\\";

    @Override
    public String generateFilename(IScope scope, String name, GenerationType type) {
        return generateFilename(scope, name, null, type);
    }

    @Override
    public String generateFilename(IScope scope, String name, String extension, GenerationType type) {
        String fileName;
        if (type == GenerationType.RECORD) {
            fileName = recordPath + name;
        } else {
            fileName = playbackPath + name;
        }
        if (extension != null) {
            fileName += extension;
        }
        log.info(fileName);
        return fileName;
    }

    @Override
    public boolean resolvesToAbsolutePath() {
        return false;
    }

    public String getRecordPath() {
        return recordPath;
    }

    public void setRecordPath(String recordPath) {
        this.recordPath = recordPath;
    }

    public String getPlaybackPath() {
        return playbackPath;
    }

    public void setPlaybackPath(String playbackPath) {
        this.playbackPath = playbackPath;
    }
}

**Comment by mondain** [comment]
Try using D:\\streams\\ or D:/streams/ for the playbackPath; java doesn't like single backslashes, they have to be escaped.

**Comment by chushiyun2015** [comment]
Thanks for your answer. I try using D:\\streams\\ and D:/streams/ for the palybakcPath; but still not work and there is no any error message in the Red5 server console.
I am new on Red5. I will appreciate it if there is any tutorials for Red5 studying.
