### ISSUE TITLE
red5_server/pom.xml jaudiotagger issue

### ISSUE THREAD

**Issue by JohnCarrie** [Red5/red5-server#131]
I am a beginner of red5_server.
I have imported red5_server project (the latest source from 
http://red5.googlecode.com/svn/java/server/trunk) in eclipse JEE(NEON).
And I've installed ivy and subclipse in my eclipse also.
But after the building of the red5_server project, only one error occured in pom.xml.

"Missing artifact org:jaudiotagger:jar:2.0.4-SNAPSHOT"

How can I fix it? Thanks.

**Comment by solomax** [comment]
You need to
1 get latest sources from github
Or
2 manually add missing artifact to your local repo

**Comment by JohnCarrie** [comment]
Thanks for your reply. 
But I have checkout the latest version from googlecode with this command.
"svn checkout http://red5.googlecode.com/svn/java/server/trunk/"

And how can I manually add missing artifact to my local repo?
Can you explain more detail? 
Thanks again.

**Comment by solomax** [comment]
Latest code is located on github
Here is how-to for maven
https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by JohnCarrie** [comment]
Thanks for your help. I'll let you know the result soon.

**Comment by JohnCarrie** [comment]
You're right. The source from the github occurred no error in pom.xml.
But another error has been occurred in source code 'RTMPSMinaloHandler.java'.
It said that 'RTMPConnection.RTMPS_STATE cannot be resolved'.
How can I fix it? Thanks.
