### ISSUE TITLE
error: Net status: NetConnection.Connect.Failed

### ISSUE THREAD

**Issue by rajeevvishva** [Red5/red5-server#132]
my system 

AMD -
46 bit OS Windows 10

i am getting error on access http://localhost:5080/installer/
but home page http://localhost:5080/ working fine...

Trying to connect to war location
Net status: NetConnection.Connect.Failed

**Comment by mondain** [comment]
The red5 war version is not actively supported, but I'm not sure if that's even what you're referring to here. Or maybe your "installer" apps is missing? Please be way more clear in the future.

**Comment by mondain** [comment]
Look at issue #180
