### ISSUE TITLE
Exception on ServiceInvoker with play method

### ISSUE THREAD

**Issue by andreslorek** [Red5/red5-server#133]
Sometimes I'm getting this exception: http://pastebin.com/eEDLFycB

I don't know if it is related, but on a session where I got this error ~20 times the audio quality was very bad (had a lot of small gaps on live transmission and recorded flv file).

I was using Red5 1.0.6 with a custom app and this red5.properties file: http://pastebin.com/LFaM8j0H

**Comment by mondain** [comment]
Next commit will log a warning if a stream cant be created for a given id; the NetStream.Fail will also be sent to the requester.
