### ISSUE TITLE
Exception on ServiceInvoker with receiveAudio method

### ISSUE THREAD

**Issue by andreslorek** [Red5/red5-server#134]
Sometimes I'm getting this exception: http://pastebin.com/5YGaUpej

I don't know if it is related, but on a session where I got this error ~20 times the audio quality was very bad (had a lot of small gaps on live transmission and recorded flv file).

I was using Red5 1.0.6 with a custom app and this red5.properties file: http://pastebin.com/LFaM8j0H

**Comment by mondain** [comment]
The next commit to HEAD will have a mod preventing a null PlayEngine from causing this message. A log level debug entry will be made where this exception was previously showing up.
