### ISSUE TITLE
Could not play mp4 video from begining

### ISSUE THREAD

**Issue by wuknife** [Red5/red5-server#138]
Red5 could not play begining of the mp4 video , I find  "if (keyFrameMeta.timestamps[i] > ts)" change to "if (keyFrameMeta.timestamps[i] >= ts)"  is ok, whicn in line 278 of  "FileProvider.java";
![github](https://cloud.githubusercontent.com/assets/9473647/12507803/1c2c9ec4-c133-11e5-9c70-40a3b165e075.png)

Is it correct ?

**Comment by mondain** [comment]
Resolved in latest push
