### ISSUE TITLE
Could not find org.red5.server.Bootstrap fresh ubunto

### ISSUE THREAD

**Issue by dev-mraj** [Red5/red5-server#140]
Hi,

just installed fresh ubunto and ``apt-get install red5-server``
but service is enable to start..
if run directly /usr/share/red5/red5.sh

then i am getting

Running on  Linux
Starting Red5
Error: Could not find or load main class org.red5.server.Bootstrap

let me know what i am missing

**Comment by mondain** [comment]
We don't maintain an apt-get version of red5, so I'm not sure where you're getting that from.
