### ISSUE TITLE
Please tutorial to install red5 on Debian Jessie 8

### ISSUE THREAD

**Issue by TheBudda** [Red5/red5-server#145]
Can you please give a tutorial for installing Red5 Server on Debian Jessie. I have been looking on the net for 5 days now and nothing works. I am running my own dedicated server with OVH running Debian Jessie 8

I would really appreciate your help

**Comment by mondain** [comment]
Here's a quick how-to: https://github.com/Red5/red5-server/wiki/Installation-on-Linux

**Comment by TheBudda** [comment]
Thank you for your quick reply.

**Comment by TheBudda** [comment]
Hi mondain,

I am sorry to bother you again. I followed the how to you sent me. When I do the start command to start red5 I am getting it hanging in Konsole (please see screenshot) 
![ssh_konsole_hangs](https://cloud.githubusercontent.com/assets/16983376/12704919/a3df8760-c85d-11e5-8333-73c40bebdf03.png)

**Comment by mondain** [comment]
Did you open your browser to http://localhost:5080/  ?

**Comment by TheBudda** [comment]
yes but I get errors (please see screenshots
![red5_home](https://cloud.githubusercontent.com/assets/16983376/12705172/ed5d4c8c-c863-11e5-9208-86d78beb8eae.png)
![red6_ install_the_demo_applications](https://cloud.githubusercontent.com/assets/16983376/12705173/ed6031e0-c863-11e5-8eba-ce7abc46cad4.png)

**Comment by TheBudda** [comment]
I dont understand the errors. I will be using red5 for djs live video streaming on my radio station but Publisher is working (please see screenshot) I am confused
![red5_working](https://cloud.githubusercontent.com/assets/16983376/12705237/3d4ab468-c865-11e5-96b8-5d52ba2d4b79.png)

**Comment by mondain** [comment]
Looks like its working to me, nevermind the async errors; if they bother you, you may google them to find out what they mean (no idea here).

**Comment by TheBudda** [comment]
I will check the errors out in time but the Publisher is working and that what I need to stream my djs. Thank you for your help I really appreciate it :)

**Comment by TheBudda** [comment]
Hi mondain, I hope you're all good your ends?
Here is a little update and me asking you for some information. I got rid of all the errors in the end. I got Red5 1.0.6 Release working very sweet and very reliable with my application. I need to be able to stream HLS, will the red5-hls-plugin work with Red5 1.0.6 Release? If you say yes is there a installation  tutorial on install this plugin?

I look will look forward to your reply

Budda

**Comment by mondain** [comment]
The open source HLS plugin isnt being maintained anymore and is a little dated. I suggest checking out Red5 Pro if you want HLS.

**Comment by TheBudda** [comment]
thanks for your quick reply. Ah really, that's a shame. With Red5 Pro
you have to take out a monthly subscription? I did look on the REd5 Pro
website and its said $55 per month. My radio station only runs off
donations and they are hard to get in most of the time

**Comment by TheBudda** [comment]
Sorry if my question above is a bit dumb, I am new with red5

Can use your red5pro-html5-hls with my Red5 Server? again, sorry if its a dumb question

**Comment by mondain** [comment]
I don't have anything to do with pricing, but you could always talk with them about your situation. The developer version offers 10 connections, no idea how many you'd need. I didn't work on the version they offer, but it was begun from the open source version; one major bonus with the pro version is that there is no Xuggler and its up-to-date with current HLS specs.

**Comment by TheBudda** [comment]
I would need more than 10 connections. I will email them and tell them
my situation. I would offer them free adverts on my station and put REd5
Pro logos on my website etc. It might help me

Thank you for your reply and help with this

Regards
Budda

**Comment by TheBudda** [comment]
Hi Paul,

I have sent you an email to your gmail account

Kind regards

Budda
