### ISSUE TITLE
RED 5 Problem

### ISSUE THREAD

**Issue by gaelson** [Red5/red5-server#152]
Hello,
I get this problem with my red 5 server.  it appears to be an issue with the red5 configuration as the server is starting but immediately dying. 

Please need help

**Comment by mondain** [comment]
Check here: https://github.com/Red5/red5-server/wiki/Runtime-Errors

**Comment by gaelson** [comment]
thank you for your help.
Unfortunately the issue is this

Attempting to connect to RMI localhost:999
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 


I've tried changing the port and disabling the firewall, but unfortunately that is not fixing it. We performed a basic install (which we usually do not perform as it's outside of scope).

What can I do?

**Comment by mondain** [comment]
RMI can be a problem and there are properties in red5.properties to configure our implementation. Try turning it off, changing the port > 1024. Two other issues that may happen is if you have software runing RMI and it conflicts or if Red5 is already running or has not stopped.

**Comment by gaelson** [comment]
Please can you show me how to check it step by step because I don't have a good knowledge. thank you

**Comment by gaelson** [comment]
Please can you show me how to check it step by step because I don't have a good knowledge. thank you

**Comment by gaelson** [comment]
Please can you show me how to check it step by step because I don't have a good knowledge. thank you

**Comment by gaelson** [comment]
Hello 
I asked a technician to install RED5 1.0 me. He did it. I need to have application to make live streaming. where to find and how to install applications?

**Comment by gaelson** [comment]
Hello 
I asked a technician to install RED5 1.0 me. He did it. I need to have application to make live streaming. where to find and how to install applications?
