### ISSUE TITLE
[Question] How to know the subscriber's playing statistics on red5 server side? 

### ISSUE THREAD

**Issue by sevengo8378** [Red5/red5-server#153]
statistics including how many bytes have received, the play length in milliseconds, and so on.

Sometimes lag occurs under publisher-server-subscriber model,  and i want to know whether it happen in publisher-server or server-subscriber phase.

Any ideas to diagnose this kind of problem is also helpful. Thx.

**Comment by mondain** [comment]
Look at the ClientbroadcastStream, PlaylistSubscriberStream, and RTMPConnection classes; there are a number of methods you can use for stats.

**Comment by sevengo8378** [comment]
Thanks mondain for your reply.
I tried PlaylistSubscriberStream, but getBytesSent() and getCurrentTimestamp() are both 0 all the time.
Any suggestions?
![image](https://cloud.githubusercontent.com/assets/461736/13097899/4af8c6a6-d560-11e5-9a5b-0d3b6009e70d.png)
