### ISSUE TITLE
java.lang.NoSuchMethodError, reason by mina

### ISSUE THREAD

**Issue by weeylink** [Red5/red5-server#156]
mina-core-2.0.11.jar compiled by java8
when I change to mina-core-2.0.9.jar this bug was disappear.

Reference of
http://stackoverflow.com/questions/25705259/undefined-reference-concurrenthashmap-keyset-when-building-in-java-8

**Comment by mondain** [comment]
Its a known issue that occurs when compiling certain code with JDK8 and running it with JDK7; this is not considered a bug in Red5 nor Mina.
