### ISSUE TITLE
Multiple stream playback fails

### ISSUE THREAD

**Issue by mondain** [Red5/red5-server#159]
# Issue

### Short description
Only one video may be played back, selection of a second video causes the application to fail.

### Environment

 [] Operating system and version: Linux 3.13.0-77-generic Ubuntu SMP x86_64 GNU/Linux

 [] Java version: 
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

 [] Red5 version: 1.0.7-SNAPSHOT (HEAD)

### Expected behavior
Any number of video selections should playback without the need to disconnect oflaDemo in between selections.

### Actual behavior
The second video selected causes the first video to stop (expected behavior) and never starts the video selected.

### Steps to reproduce
1. Start the server
2. Open browser to oflaDemo
3. Connect
4. Select a video and watch it playback
5. Select a second video; this is were the bug occurs

**Comment by solomax** [comment]
According to Wireshark 1.0.7 acts not the same as 1.0.6
both receives
setBuffer
createStream
deleteStream
sequence

1.0.6 answers with 2 _result messages
1.0.7 answers with 1 _result message

I guess this is because deleteStream command is not being decoded due to bad header parsing of "createStream" command

will try to debug it tomorrow

**Comment by solomax** [comment]
It seems like I stuck on this one :(
According to the logs and wireshark dumps RTMPProtocolDecoder::decodeBuffer method receives incomplete buffer (with reduced length)

need your help on this, could you please tell me why is this possible?

details:
According to wireshark packet should be: 4200000000000a04000300000000000013888300152b02000c63726561746553747265616d00401000000000000005430000010000221402000c64656c65746553747265616d00000000000000000005003ff0000000000000
According to red5 log the packet is:
4200000000000a04000300000000000013888300152b02000c63726561746553747265616d00401000000000000005430000010000221402000c64656c657465

what is the reason packet is being cut on 64 byte?

**Comment by solomax** [comment]
Additional question:

https://github.com/Red5/red5-server-common/blob/master/src/main/java/org/red5/server/net/rtmp/codec/RTMPMinaProtocolDecoder.java#L73

buf.put is "relative" operation, I see no places buf is being emptied, is it "by design"?

**Comment by mondain** [comment]
The buf is consumed to create the objects in decodeBuffer; after being consumed the buf is compacted, if I'm not mistaken. There are buf.clear calls, but I don't believe the are in these decode blocks.

**Comment by solomax** [comment]
Why I'm asking: "buffer after" contains nothing in common comparing to "buffer before".

The problem with this issue: initial 64 byte chunk is read, then not being filled with additional bytes :(
not sure how to debug it :(

**Comment by mondain** [comment]
I'd honestly like to get rid of that session buffer, but we seem to need it to handle crappy connections. There's got to be an easier way than this to handle both good and bad/slow connections.

**Comment by solomax** [comment]
should be fixed with: https://github.com/Red5/red5-server-common/pull/36

**Comment by solomax** [comment]
OK
here is the bad packet:
040043e500010108010000006a446dd52db76c85ccdcb8607c31c68888888888b86dba6ddbb66dafaaaafeffffffffffffffffffbf4e483b53a0a713983d80eed01ff8e1e1f0707838ffff7ffc25464d4a0b6bb80a1fc89c64f794082d7b3a18edbeea44d49acfa834ba7d87684569aa42e003c0d5bedb0209b60ec9fb0c293cd94fb2d25dfd50faa218ab80420000000000040100000101c41a2756f299ac4f91d59da8dca393240875824cf8f2b45a8dcda7f4c5b22c5696b86b3e5f28798207bcf1c091c13899c8126b1dead534cddfa94e084a58d245e11fe066ae31a825915521e7548d4e1548139bfc4b8fc12355b0d97c9c723ab632d980c5658c4479aca5c8445cf556909267dd172eef5a48f5acc896d6acb3faaf85

According to Wireshark it is "Set Chunk Size 257|Audio Data"

Unfortunately for some unknown reason "Set Chunk Size 257" packet is in the middle of "Audio Data"
Can you explain this?

**Comment by solomax** [comment]
@mondain any hint will be highly appreciated :)

**Comment by mondain** [comment]
I really don't know; could it be that the bytes are mixed together in error?

**Comment by solomax** [comment]
Wireshark parses it correctly somehow :(

mixed message is: "420000000000040100000101c4"

**Comment by mondain** [comment]
If I understand correctly, chunk messages should come on one channel and
audio messages on another; channel 2 or 3 for chunk and 5 or 6 for audio;
so could it possible that the channel read is wrong?

**Comment by solomax** [comment]
Yes it is: "chunk stream 2" and "chunk stream 4"
I have no idea why it is mixed :(

**Comment by mondain** [comment]
Maybe each channel has its own chunk size? I really dont know.

**Comment by tdj-br** [comment]
@solomax Just got a message from Paul asking for some help. It seems you already fixed the problem. I haven't looked into it yet, can you confirm it's fixed? Or should I take a look on that?

Thanks

**Comment by solomax** [comment]
Hello @tdj-br, unfortunately all fixes are not final :(
I believe code is improved a lot, everything works as expected .... util I'm starting audio/video broadcasting
will try to perform additional debugging later tonight

your help will be highly appreciated

**Comment by solomax** [comment]
Hello @mondain, I'm trying to simplify my setup for this issue
While using http://localhost:5080/demos/simpleBroadcaster.html
I got 
```
[WARN] [RTMPConnectionExecutor-2] org.red5.server.net.rtmp.RTMPHandler - Scope not found
org.red5.server.exception.ScopeNotFoundException: Scope not found: oflaDemo in null
```

http://localhost:5080/oflaDemo is available, http://localhost:5080/demos/ofla_demo.html works as expected
what can be the problem?

**Comment by tdj-br** [comment]
@solomax: the original "Steps to reproduce" still reproducing the problem?

I'll have some time tonight and will take a look.

    Start the server
    Open browser to oflaDemo
    Connect
    Select a video and watch it playback
    Select a second video; this is were the bug occurs

**Comment by solomax** [comment]
No, this is solved

New problem is related to the live stream: audio/video from the camera
I'm using OpenMeetings to reproduce this, it's too heavy for testing :(

while trying to simplify the setup I find out http://localhost:5080/demos/simpleBroadcaster.html is not working :(
Maybe @mondain can quickly fix it

**Comment by mondain** [comment]
I can look into it, but if its fla based we're kinda screwed there since I
don't have flash pro anymore.

**Comment by mondain** [comment]
I suggest using the publisher demo instead; which I also can't recompile.

**Comment by solomax** [comment]
I believe the issue is on the server: "ScopeNotFoundException"
In case it is client based I can try to create as3 project

**Comment by solomax** [comment]
Thanks for merging :)
I'm afraid I need to refactor RTMPProtocolDecoder a little bit
currently it doesn't handle "mixed" messages very well
will report back here

**Comment by solomax** [comment]
for some unknown reason internal buffer is ~65k (max packet is ~32k)
the server is almost unable to process incoming messages

trying to catch the root cause

**Comment by solomax** [comment]
http://localhost:5080/demos/publisher.html works, but with some visual artifacts :(
sometimes parsing fails, but not stable :(

@tdj-br Maybe you can see what is wrong using publiser?
Steps:
```
1) rebuild all modules:
red5-parent
red5-service
red5-io
red5-server-common
red5-server

2) create red5-server assembly
3) run red5, install oflaDemo
4) go to http://localhost:5080/demos/publisher.html 
5) start broadcasting using 1 browser and watch using another
```

**Comment by solomax** [comment]
To see the issue you need both audio and video (it seems in this case packets are being mixed and we are not processing them as expected :(
will try to update RTMPProtocolDecoder::decodePacket to be more elegant and maybe it will help

**Comment by solomax** [comment]
I believe this issue can be closed
Additional investigation is required according to transferring numbers (behavior was changed since 1.0.6, but maybe this can be workarounded)

**Comment by mondain** [comment]
Agreed. What do you mean by "transferring numbers", do you mean sending Number / Integer values in AMF?

**Comment by solomax** [comment]
on the flash side I'm using 
```
var streamId = 5;
publish(streamId);

```and
```
var streamId = 5;
play(streamId);

```
while executing "play" stream being played is not "5", but "5.0"
it can be workarounded by using 
```
var streamId = "5";
play(streamId);

```
but this behavior differs from 1.0.6 ....

**Comment by mondain** [comment]
Does wireshark show the value of "5" as an integer or number? In AMF0 there
aren't supposed to be any Integers, we had a hack in-place with all the
previous versions of Red5.

**Comment by solomax** [comment]
Actually it's not a big deal :)
I have already fixed the code, I have mentioned this just to point to the "API break": things that were working in 1.0.6 are silently broken in 1.0.7
Maybe it worth to create wiki page regarding this or something ....

**Comment by mondain** [comment]
Yes, I agree, but these things tend to fall through the cracks (i forget to
document them). I wish there was an elegant way to handle something like
this, rather than forcing the string; although I believe that a stream name
is supposed to be a string.

**Comment by solomax** [comment]
Strings are OK :)
the only showstopper for me right now is red5-client :)

**Comment by mondain** [comment]
Client should be using the same encoder/decoder or at least the processing
parts; what is the issue you're seeing?

**Comment by solomax** [comment]
Client is unable to connect to server:

[WARN] [NioProcessor-3] org.red5.server.net.rtmp.InboundHandshake - Client digest verification failed
[WARN] [NioProcessor-3] org.red5.server.net.rtmpe.RTMPEIoFilter - Client was rejected due to invalid handshake

**Comment by mondain** [comment]
Interesting, that was working.. the handshake is the bane of my existence.
