### ISSUE TITLE
Some videos are not playing in oflaDemo application

### ISSUE THREAD

**Issue by yanalavishnu** [Red5/red5-server#161]
# Issue

### Short description
Some videos in oflaDemo application are not playing, Server throws continuously __Error on channel position / read__. Why does this happen? Example file path:- streams/022016/23451/3294023.mp4. Does the file path causing this problem?

### Environment

[] Java version: 7
[] Red5 version: 1.0.6

### Logs
__[Red5 Error log](http://pastebin.com/478bPYEz)__

**Comment by mondain** [comment]
In this case there was an issue reading your mp4 file; I dont see the reason in your log, but whatever it was caused the file channel to be closed.

**Comment by yanalavishnu** [comment]
Same video(mp4) didn't play yesterday. But it is playing today. That means there is no issue in reading my mp4 file.

**Comment by mondain** [comment]
There's a delta somewhere or there would be nothing wrong anywhere.
