### ISSUE TITLE
rtpm/jwpalyer in red 5

### ISSUE THREAD

**Issue by Sligths** [Red5/red5-server#171]
it's about the red5/ oflaDemo that ican't use it's rtpm to trans-stream.
i have import jwplayer.js  into the html.
and here is the code:
__<script type='text/javascript'>
 jwplayer('mediaspace').setup({
    'flashplayer': 'player.swf',
    'file': '001.flv',
    'streamer':'rtmp://localhost/oflaDemo',
    'controlbar': 'bottom',
    'width': '848',
    'height': '360',
	'image':'logo.png'

	});__

it can work perfect without  " 'streamer':'rtmp://localhost/oflaDemo' " as i can see 011.flv,
but it would loaning..... if it get streamer****
of course i have try in the Classic demo and i also work perfect.
 help me plz.

**Comment by mondain** [comment]
This doesnt make much sense to me; you're missing quite a lot of detail as to what is wrong. If you have a problem using jwplayer, go to https://github.com/jwplayer/jwplayer and see what you may be misunderstanding.
