### ISSUE TITLE
JAVA_HOME environment variable not set!

### ISSUE THREAD

**Issue by mhamdisemah** [Red5/red5-server#173]
# Issue

### Short description
i added java_home to environment variable but it still showing this error 

### Environment

[] Operating system and version: windows 10 64 bit
[] Java version:1.7 32 bit
[] Red5 version:1.0.3

### Actual behavior
java_home

**Comment by mondain** [comment]
The batch script is not seeing the environment variable; if you set it while the run window was open, you'll need to close the window and try it again as it won't see the variable if added when open. 
http://www.mkyong.com/java/how-to-set-java_home-on-windows-10/
