### ISSUE TITLE
mp4 file wrong speed or ...

### ISSUE THREAD

**Issue by nirtik** [Red5/red5-server#174]
# Issue
### Short description

mp4 file wrong speed or some file info detect error
### Environment

[] Operating system and version:
Ubuntu 14.04.3 LTS

[] Java version:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

[] Red5 version:
red5-server-1.0.7-M10
### Expected behavior

i click on play in player and file start playing
### Actual behavior

start buffering, long buffering and after that playing fast. Playing faster at 5-10 times. Buffering 4 second video more then 30 second(file size 50MB)
### Steps to reproduce

rtmp server:   rtmp://185.26.218.140:1936/live/
file    1_111.mp4  - has wrong speed or time in red5.(when i print buff time its look like normal from 1 to 4 sec but long biffering and very fast play after buffering)
file    1_111.flv - normal play, the same encoding.

http://185.26.218.140/videos/streams/1_111.mp4
browser play with normal speed

**Comment by mondain** [comment]
Buffering is up-to the player, so I'd start there for that item. As far as playback speed, I assume its something in the moov boxes that may not be compatible with our reader.

**Comment by mondain** [comment]
The MP4 reader has been refactored for version 1.0.9, please retest with latest
