### ISSUE TITLE
How to Install red5 server in mac os x 10.11.1

### ISSUE THREAD

**Issue by chinnuios** [Red5/red5-server#176]
# Issue

### Short description
I am trying to install red5 server, but i don't know, how to install in mac ?? i get the red5 server 1.0.5 from " https://github.com/Red5/red5-server/releases/tag/v1.0.5-RELEASE." so  please tell me process  of install red5 server in mac.

Thank you

### Environment

[] Operating system and version: os x 10.11.1
[] Java version: 1.8
[] Red5 version: 1.0.5

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
We don't distribute a dmg anymore if that's what you want. I suggest grabbing one of the tar.gz files and going from there; there is no "install" process.
