### ISSUE TITLE
How to install Red5 1.0.7 on Ubuntu

### ISSUE THREAD

**Issue by rinodung** [Red5/red5-server#178]
# Issue

### How to install Red5 1.0.7 on Ubuntu
I look at wiki https://github.com/Red5/red5-server/wiki/Installation-on-Linux
but Red5 1.0.7 with different structure(red5.sh not found)

### Environment

[] Operating system and version: Ubuntu 14.04
[] Java version: 1.7
[] Red5 version: 1.0.7

**Comment by mondain** [comment]
If you don't have a red5.sh in your tarball, you've downloaded the wrong file from https://github.com/Red5/red5-server/releases
The scripts are also available here: https://github.com/Red5/red5-server/tree/master/src/main/server
