### ISSUE TITLE
How to ban other site access streaming media server？

### ISSUE THREAD

**Issue by fmpoffice** [Red5/red5-server#181]
How to ban other site access streaming media server。
My website is www.a.com, but its website is www.b.com, how to stop b.com copy my RMTP address on to play

![123](https://cloud.githubusercontent.com/assets/11001031/15446225/12d513ee-1f4b-11e6-8b74-1621e0502fec.png)

**Comment by mondain** [comment]
I answered this on SO awhile ago, the links are broken now, but the details are covered in the answer: http://stackoverflow.com/a/3631983/127938

**Comment by mondain** [comment]
More detail here: https://wiki.dlib.indiana.edu/display/VarVideo/Red5+Streaming+Server
