### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by isantolin** [Red5/red5-server#182]
# Issue

### Short description
Changelog file is updated up to 1.0.2 but current version is 1.0.8

**Comment by mondain** [comment]
I'll put it on my to-do list https://github.com/Red5/red5-server/blob/master/changelog.txt

**Comment by mondain** [comment]
On second thought, this probably isn't going to happen; the project consists of several projects / repos and I don't have the time to keep up with changes. My best solution is to do a github search with whatever advanced parameters would provide the info between tags.
