### ISSUE TITLE
help,Build Path Problem?

### ISSUE THREAD

**Issue by sunxu3074** [Red5/red5-server#183]
# Issue

### Short description

Project 'red5-server' is missing required library: '/Users/sunxu/.m2/repository/org/apache/mina/mina-core/2.0.14-SNAPSHOT/mina-core-2.0.14-SNAPSHOT.jar'	red5-server		Build path	Build Path Problem

Project 'red5-server' is missing required library: '/Users/sunxu/.m2/repository/org/apache/mina/mina-integration-beans/2.0.14-SNAPSHOT/mina-integration-beans-2.0.14-SNAPSHOT.jar'	red5-server		Build path	Build Path Problem

> Is my install problem or other things?

1.  I install maven on my Mac and install maven plugins for eclipse .
2.  Clone red5-server .
3.  Use mvn eclipse:eclipse in red5-server directory .
4.  Then occur some problem lick above.

### Environment

[] Operating system and version: Mac OS X Yosemite 10.10.5
[] Java version: 1.8
[] Red5 version: 1.0.8-M1

### Expected

I didn`t used maven ever . Should I use __Maven__  and __Build from Source__ before __Eclipse__? Expecte for your answer . My English is so bad , forgive me .

**Comment by fmpoffice** [comment]
change maven pox.xml

http://mvnrepository.com/artifact/org.apache.mina/mina-core

**Comment by mondain** [comment]
That was an error on my part for using my locally built version of mina.
