### ISSUE TITLE
red5 mobile cross domain is possible ?

### ISSUE THREAD

**Issue by reutorah** [Red5/red5-server#186]
# Issue

### Short description
I want to know if mobile cross domain is possible with red5 free versions not pro one.

### Environment

[] Operating system and version:
[] Java version:
[] Red5 version:0.8

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
Yes, but you have to implement everything done in Red5 Pro by yourself.

**Comment by reutorah** [comment]
I don't want to use red5 pro I don't have money.

I want to know how I can use red5 mobile cross domain with free versions. Its good for making ppsin android with red5 for live streaming like audio chat room.

Can you suggest me how I can do it for free.

**Comment by mondain** [comment]
I'm not trying to be funny here, but "how do I, do it for free?", has a simple answer, you do it yourself. You google search for "android rtmp" or "ios rtmp" and learn from there.

**Comment by odiszapc** [comment]
No money — no honey.

**Comment by reutorah** [comment]
If no money no honey post a tutorial on how to mobile cross domain using red5 free media server.

**Comment by odiszapc** [comment]
For money.
