### ISSUE TITLE
some problem with memory

### ISSUE THREAD

**Issue by nirtik** [Red5/red5-server#188]
# Issue

### Short description
12 online cam. monitor which reconnect cams to red5

for java i set 3g limit of memory  -Xmx2g

when start:
time: 16:18
 5576 root      20   0 6613140 993244  18596 S  14.1 25.1   1:40.71 java
time: 16:31
 5576 root      20   0 6613140 1.543g  15328 S  46.8 40.9   6:07.48 java
time: 16:50
 5576 root      20   0 6613284 1.789g   8528 S  27.2 47.4  13:00.67 java
time: 17:12
 5576 root      20   0 6613284 1.939g   8720 S  33.9 51.4  21:10.62 java
time: 17:17
 5576 root      20   0 6613284 1.708g   8788 S  53.3 45.3  23:04.32 java
time: 17:46
 5576 root      20   0 6615332 1.965g   8076 S  44.3 52.1  33:20.52 java
time: 18:34
5576 root      20   0 6615332 1.829g   8128 S  38.9 48.5  51:16.12 java
time: 20:47
 5576 root      20   0 6644592 2.976g   4728 S 288.4 78.9 103:57.38 java

that log
http://217.23.11.150/red5-iss.log

other log with memory error
2016-06-04 19:47:29,467 [RTMPConnectionExecutor-2] ERROR org.red5.codec.AVCVideo - Failed to buffer interframe
java.lang.OutOfMemoryError: GC overhead limit exceeded

http://217.23.11.150/red-log.log

### Environment
Operating system and version:
Ubuntu 16.04 LTS

Java version:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Red5 version:
red5-server-1.0.7-RELEASE-server

**Comment by mondain** [comment]
There is no bounding on the interframe collection in `AVCVideo`, that may be the problem here. Would you mind setting the logger to __TRACE__ on `org.red5.codec.AVCVideo` so that we can see the interframe count? Also here's a link to the class in question: https://github.com/Red5/red5-io/blob/master/src/main/java/org/red5/codec/AVCVideo.java

Here's the `logback.xml` entry to make:
```xml
<logger name="org.red5.codec.AVCVideo" level="TRACE" />
```

**Comment by nirtik** [comment]
i add that param and restart. 10 minutes http://217.23.11.150/red5_AVCVideo_trace.log

**Comment by mondain** [comment]
Highest that i see is 248, but there are a lot in the 100's, I don't see a need for that many interframes being stored, but I'm not an expert on AVC/h.264.

**Comment by nirtik** [comment]
I can give you more information if you say how.
Maybe i get AVCVideo error when no more space and other class eat space.
For example i have problem with translation name. I sometime restart cams and get error from red5 like translation name is used. And to fix that i need restart server. Now i use dynamically names and dont now how many translation in that time are broken.

**Comment by mondain** [comment]
Streams should be cleaned up and resources cleared after a period of inactivity.

**Comment by mondain** [comment]
In version 1.0.8-M5 and newer, you can adjust the interframes in AVCVideo, this may be a solution for your installation; try it and let us know.
