### ISSUE TITLE
Problem getting sudo update-rc.d red5 defaults set, and audio problems.

### ISSUE THREAD

**Issue by Smeagol777** [Red5/red5-server#189]
I'm getting these errors when running the command: sudo update-rc.d red5 defaults

insserv: Script red5 is broken: incomplete LSB comment.
insserv: missing Default-Start:' entry: please add even if empty. insserv: missingDefault-Stop:' entry: please add even if empty.
insserv: Default-Start undefined, assuming empty start runlevel(s) for script red5' insserv: Default-Stop undefined, assuming empty stop runlevel(s) for scriptred5'

Using Ubuntu 16.04, Java 8 is installed. Currently using Red5-1.0.7-Release.

I also have audio problems ever since using red5, voice repeats and sounds horrible, like it's running through a filter. (demon like sounds.lol) I've tried other computers with different sound cards or onboard chipsets and headphones with speakers output off.(I have no problems with other software, games, TeamSpeak, etc.) I've noticed other users don't seem to have this problem, so I guess it's something on my end. But maybe someone has run into this before. (Tried disabling boost, input levels, etc.) 

My main concern is the getting Red5-1.0.8 Milestone 2 running.

Thanks for your time,
Smeagol777

**Comment by mondain** [comment]
I just added these to red5-service here https://github.com/Red5/red5-service/commit/7940b919c7f404caedff7bad90c217e85d719dd7 they will be available in 1.0.8-M5 or Release, whichever comes next.
