### ISSUE TITLE
AbstractQueuedSynchronizer

### ISSUE THREAD

**Issue by nirtik** [Red5/red5-server#190]
I write script which try to write some video in red5. If i cant write i save log and restart red5.
Some other error in log: http://217.23.11.150/iss.txt I try to create other issue when i check other log file.
### Short description

for that log files i set constant test name "server_480" and sometimes i see that error:
ERROR o.red5.server.stream.StreamService - Bad name server_480
2 days ago i change to dynamic thread name and a dont see any AbstractQueuedSynchronizer errors.

disconnected or connected

(red5_1466181341.log)
WARN  o.r.s.net.rtmp.RTMPMinaConnection - Interrupted while waiting for write lock. State: disconnecting
java.lang.InterruptedException: null
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)

(in all log files)
WARN  o.r.s.net.rtmp.RTMPMinaConnection - Interrupted while waiting for write lock. State: connected
java.lang.InterruptedException: null
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)

(red5_1466144332.log, red5_1466074354.log)
WARN  org.red5.io.flv.impl.FLVReader - Exception acquiring lock
java.lang.InterruptedException: null
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)

http://217.23.11.150/red5_1466074354.log
http://217.23.11.150/red5_1466086183.log
http://217.23.11.150/red5_1466086617.log
http://217.23.11.150/red5_1466102763.log
http://217.23.11.150/red5_1466144332.log
http://217.23.11.150/red5_1466161396.log
http://217.23.11.150/red5_1466170070.log
http://217.23.11.150/red5_1466181341.log
### Environment

Operating system and version:
Ubuntu 16.04 LTS

Java version:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Red5 version:
red5-server-1.0.7-RELEASE-server

**Comment by ncdanh90** [comment]
Hi! I got the same problem. I google it and I find a solution at [https://groups.google.com/forum/#!topic/red5interest/kAkf75qvaVs](url) 

This is my code in StreamService in method public void publish(String name, String mode)
`IBroadcastScope bsScope = getBroadcastScope(scope, name);
            if(bsScope != null && !bsScope.getProviders().isEmpty()) {
                deleteStream(bsScope.getClientBroadcastStream().getConnection(), bsScope.getClientBroadcastStream().getStreamId());
            }
            bsScope = getBroadcastScope(scope, name);
            if (bsScope != null && !bsScope.getProviders().isEmpty()) {
                // another stream with that name is already published			
                sendNSFailed(streamConn, StatusCodes.NS_PUBLISH_BADNAME, name, name, streamId);
                log.error("Bad name {}", name);
                return;
            }`

**Comment by mondain** [comment]
Streams take a short time to wrap up what they are doing when finished; this must be taken into account before attempting to use the same stream name.
