### ISSUE TITLE
Source code for Red5 demos

### ISSUE THREAD

**Issue by mpd518** [Red5/red5-server#194]
# Issue

### Short description
The Red5 source code distribution only contains src for Red5 itself, but not for the demos under \server\webapps\root\demos. It is usually the expectation that the demos src code are included as part of of the distribution.

### Environment

[] Operating system and version: Win/Linux/MacOs
[] Java version: JRE 1.7
[] Red5 version: 1.0.8 M5

### Expected behavior
Able to find src code for the SWF files under \red5-server-1.0.8-M5\red5-server\webapps\root\demos.

### Actual behavior
Could not find src code for the SWF files under \red5-server-1.0.8-M5\red5-server\webapps\root\demos.

### Steps to reproduce
1. Download latest public src package from https://github.com/Red5/red5-server/archive/v1.0.8-M5.zip and unzip.
2. Goto \red5-server-1.0.8-M5\red5-server\webapps\root\demos
3. Couldn't find the src code for the SWF demos, only the SWF binaries.

### Logs
None.

**Comment by mondain** [comment]
Source for the flash demos is here: https://github.com/Red5/red5-flash
Also for most of the webapps, here: https://github.com/Red5/red5-examples
Separate chat demo: https://github.com/Red5/red5-websocket-chat
For others, take a look around the Red5 org on github before posting issues like this.. thanks :)
