### ISSUE TITLE
AAC live streaming: no audio unless listener is connected before stream is published

### ISSUE THREAD

**Issue by adamdullenty** [Red5/red5-server#195]
### Short description
Audio streams encoded in AAC produce no audio for new clients connecting after the publisher is connected. Clients already connected pick up the audio fine if the publisher is later connected or reconnected.

See https://groups.google.com/forum/#!topic/red5interest/sGWQ5kn9PP4 - it's quite an old thread, but the symptoms seem identical.

My question is basically: has this been resolved? As the above comments went dead.

### Environment

* Operating system and version: Server: Alpine 3.3 on Docker, Listener: Ubuntu 15.10 and 16.04 (Chromium via the Red5 Publisher Demo)
* Java version: Java 8
* Red5 version: We've tried 1.0.6, 1.0.7 & 1.0.8m5

### Expected behavior
The listener should be able to connect to an AAC stream at any point after it's been published and hear the audio stream.

### Actual behavior
The listener connects to the stream, buffer fills, but produces no audio. The listener can only hear the AAC stream if they are connected to that server/channel before the stream is published. Once  hearing the audio fine, reconnecting the listener again produces no audio.

We have experienced this a few times recently with different companies, with various hardware and software encoders, yet we've never had any issues with other codecs e.g. Speex so we are suspecting that this is a Red5 issue, especially given the above Google Groups topic and the fact that the symptoms seem identical.

### Steps to reproduce
1. Publish a live audio stream to a red5 server / channel using RTMP and AAC as the codec
2. Connect to red5 server / channel using RTMP as a listener - I'm using the Red5 Publisher Demo
3. Notice that you see the buffer fill but can't hear any audio
4. Disconnect the publisher and reconnect, and in the logs for the listening player you'll see PublishNotify, metadata, and the buffer fills, and you can then hear the audio
5. Disconnect/reconnect the listener, you'll see the buffer refill but again not hear any audio.

### Logs
https://gist.github.com/adamdullenty/d625dc757d6460c4af1109210a879afd

**Comment by mondain** [comment]
I assume your broadcaster / publish app (possibly FMLE) is providing the AAC input? This sounds like the AAC config data isn't being sent to new subscribers, that's the first place I'd look. However, we do use AAC in Red5 Pro and don't have an issue that I know of at this time.

**Comment by marin85** [comment]
I also have the same AAC problem as reported by adamdullenty. I am using the red5 1.0.9 version and I need to fix this problem using this platform. In these years have you solved the problem or there are workaround to fix it?
