### ISSUE TITLE
Just few questions

### ISSUE THREAD

**Issue by giggioman00** [Red5/red5-server#196]
Hello. Is it possible to use Red5 for an on-demand streaming server?
Is it compatible with http request?
Also, where can I find a tutorial for configuring this? I tried everywhere but I can't find anything

Thank you

**Comment by mondain** [comment]
Red5 will do on-demand or VOD as its commonly referred to out-of-the-box. There's no configuration needed beyond the default for basic VOD. Install the server and drop your flv or mp4 files in `red5/webapps/vod/streams` directory and request those files via your Flash client.
