### ISSUE TITLE
Sign binaries for Mac

### ISSUE THREAD

**Issue by fulldecent** [Red5/red5-server#198]
# Issue

### Short description
This cannot run on Mac with standard security settings.

### Environment

OS X 10.11
[x] Red5 version: Milestone 6

![screen shot 2016-08-09 at 12 49 55 am](https://cloud.githubusercontent.com/assets/382183/17504934/4c2d29d8-5dcb-11e6-98a6-8bba0fc6b43c.png)

**Comment by mondain** [comment]
We don't sign our jars or in most cases create special rules for each operating system on which Java runs. If you know of a meta tag or whatever that osx is looking for we might add it, but otherwise this probably won't go anywhere.
