### ISSUE TITLE
Replay mp3 file, always show the stop status.

### ISSUE THREAD

**Issue by wsrfzd** [Red5/red5-server#203]
### Short description
Two problem：
1.Play mp3 files for the first time is normal, but when i refresh the page to replay the file, always show the stop status.
2.Displays an mp3 file time error.
### Environment
Operating system and version: windows, linux
Java version: jdk1.7, jdk1.8
Red5 version: red5-server-1.0.7-RELEASE, red5-server-1.0.8-M7

### Expected behavior
Normal play mp3.

### Actual behavior
Can't normal play mp3.

### Steps to reproduce
1. Start red5 server.
2. Play is normal for the first time.
3. Refresh the page to replay, can't normal play mp3.

### Logs
Displays an mp3 file time error：
![image](https://cloud.githubusercontent.com/assets/12988777/17838743/478a7e54-6806-11e6-8d9c-9144d179e314.png)

Refresh the page to replay, can't normal play mp3 and always show the stop status：
![image](https://cloud.githubusercontent.com/assets/12988777/17838780/559bfde6-6807-11e6-84c4-d9a6c7ecf8d4.png)

**Comment by mondain** [comment]
Which player are you using for my reference?

**Comment by wsrfzd** [comment]
CuPlayer

**Comment by mondain** [comment]
I can't reproduce this; the best that I can tell is that something is being cached on the device. The mp3 file being requested is streamed and each request to playback is separate from any previous request; there is no caching or sharing on the server-side.
