### ISSUE TITLE
Cannot run RTMP Server : ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ziedakremi** [Red5/red5-server#205]
# Issue

### Short description
I have installed in my local machine Red5-1.0.6-SNAPSHOT.exe	 (Windows Installer version)
with those configurations 
- Ip adress : 0.0.0.0
- HTTP port: 5080

I can run Red5 web page (http://127.0.0.1:5080/) but  got these errors

 **In Dos console**
 
[WARN] [NioProcessor-12] org.red5.server.net.rtmp.RTMPMinaIoHandler - Force close - session: 11
[WARN] [NioProcessor-13] org.red5.server.net.rtmp.RTMPMinaIoHandler - Force close - session: 12
[WARN] [NioProcessor-12] org.red5.server.net.rtmp.RTMPMinaIoHandler - Force close - session: 11
[WARN] [NioProcessor-13] org.red5.server.net.rtmp.RTMPMinaIoHandler - Force close - session: 12
[INFO] [NioProcessor-12] org.red5.server.net.rtmp.RTMPMinaIoHandler - Close already forced on this session: 11
[INFO] [NioProcessor-13] org.red5.server.net.rtmp.RTMPMinaIoHandler - Close already forced on this session: 12

**in Chrome** 

POST http://localhost:1935/fcs/ident2 net::ERR_EMPTY_RESPONSE localhost:1935/open/1:1 
POST https://localhost:1935/open/1 net::ERR_CONNECTION_CLOSED localhost:1935/open/1:1 
POST http://localhost:1935/open/1 net::ERR_EMPTY_RESPONSE localhost/open/1:1 
POST https://localhost/open/1 net::ERR_CONNECTION_REFUSED localhost:80/open/1:1 
POST https://localhost:80/open/1 net::ERR_CONNECTION_REFUSED localhost:443/fcs/ident2:1 
POST http://localhost:443/fcs/ident2 net::ERR_CONNECTION_REFUSED localhost/fcs/ident2:1 
POST http://localhost/fcs/ident2 net::ERR_CONNECTION_REFUSED localhost:443/open/1:1 
POST http://localhost:443/open/1 net::ERR_CONNECTION_REFUSED localhost/open/1:1 

### Environment

[] Operating system and version: Win
[] Java version: jdk1.7, jdk1.8
[] Red5 version: setup-Red5-1.0.6-SNAPSHOT.exe	

### Actual behavior

Chrome navigator inspector (console /log)

POST http://localhost:1935/fcs/ident2 net::ERR_EMPTY_RESPONSE localhost:1935/open/1:1 
POST https://localhost:1935/open/1 net::ERR_CONNECTION_CLOSED localhost:1935/open/1:1 
POST http://localhost:1935/open/1 net::ERR_EMPTY_RESPONSE localhost/open/1:1 
POST https://localhost/open/1 net::ERR_CONNECTION_REFUSED localhost:80/open/1:1 
POST https://localhost:80/open/1 net::ERR_CONNECTION_REFUSED localhost:443/fcs/ident2:1 
POST http://localhost:443/fcs/ident2 net::ERR_CONNECTION_REFUSED localhost/fcs/ident2:1 
POST http://localhost/fcs/ident2 net::ERR_CONNECTION_REFUSED localhost:443/open/1:1 
POST http://localhost:443/open/1 net::ERR_CONNECTION_REFUSED localhost/open/1:1 

### Logs
http://pastebin.com/7J3gmhZh

**Comment by mondain** [comment]
Use a newer version please; I just fixed the installer and builds will happen again on Apache Jenkins. For now you can use this one: https://dl.dropboxusercontent.com/u/7316897/red5/latest/setup-Red5-1.0.8-M10.exe
