### ISSUE TITLE
Guest Functionality (Video packet run time processing)

### ISSUE THREAD

**Issue by VJ-Vicky** [Red5/red5-server#206]
# Issue
Unable able to create a runtime processing logic.
### Short description
I want to able to process a live stream packet and create a video where half screen shows video of stream ABC and other half shows video of stream XYZ

### Environment

Amazon AMI on EC2 instance
Java 1.8
Red5Pro 1.3.0

### What I am trying to accomplish here.

We are creating a iOS app (Similar to YouNow) in this app user can broadcast and many users can subscribe to that stream this is the basic version. Now what we want to implement is guest functionality in the application where a subscriber become a guest for a broadcasting stream.

Lets take an example Adam is broadcasting and there are 10 subscribers at the moment. Now at 3 minute mark Adam chooses John to be a guest on the stream then the view will get divided into two and half screen will show of Adam & other half of John. Now at 5 minute mark John leave the broadcast then the view will become again stream of Adam only. At 8 minute mark Adam chooses Rihana to be a guest then again same thing happens and view get divided into two for all broadcaster and subscribers. When she leaves at 13 minute mark the view become of Adam only.

Now we are able to do this using multiple stream subscribing, the problem comes in saving this video and watch it later. In that video whole broadcast of Adam will be there moreover there will be guest according to their time-stamps. Means John and Rihana will be there as a guest in saved video at 3 and 8 minute mark respectively.

For this functionality I know that I have to write packet to packet processing logic. Now please help me out in this problem.

Thank You. Hope to get a reply from you soon :)

Regards,
Vishwajeet

**Comment by mondain** [comment]
You can attach a [listener](https://github.com/Red5/red5-server-common/blob/ce8229d6a45ce0390fc699afe35e0b67d762790f/src/main/java/org/red5/server/api/stream/IStreamListener.java) to your streams and do whatever you like to your packets; that's part of the beauty of having access to all this Red5 source. Heres where the Recording listener is attached for recording: https://github.com/Red5/red5-server-common/blob/9721800ee16e6f604e476de473671e9118eb677c/src/main/java/org/red5/server/stream/ClientBroadcastStream.java#L687

In `packetReceived` you'll get the [IStreamPacket](https://github.com/Red5/red5-server-common/blob/ce8229d6a45ce0390fc699afe35e0b67d762790f/src/main/java/org/red5/server/api/stream/IStreamPacket.java) which can be checked for the type you want, such as [VideoData](https://github.com/Red5/red5-server-common/blob/6fa501bef26970c3659300463e8b40e96a462fb0/src/main/java/org/red5/server/net/rtmp/event/VideoData.java)

**Comment by VJ-Vicky** [comment]
Hello Paul,

Thanks for such a quick response. I have created a listener as suggested by you, and I am able to identify a packet using IStreamPacket, but now I am stuck at how do I stitch that packet to another packet or video file, so that the recorded video will be a video with half of broadcaster(Adam) and half of guest (John). 

Hope to get a response from you soon :) :+1:

**Comment by mondain** [comment]
That part of your functionality is outside my skill set; in most cases, what you're trying to do would be coded up using an ffmpeg filter or something similar.

**Comment by VJ-Vicky** [comment]
Hello Paul,

Good Morning. Can you please guide me to the logic where Red5 actually saves the video into flv file and also can you please elaborate what is "FILENAME.flv.ser" & "FILENAME.flv.info" use. Please reply to both the questions.

Thank You for quick responses :)

**Comment by mondain** [comment]
info is for constructing the meta data and flv header
ser is serialized stream data

**Comment by mondain** [comment]
Taking a look at the FLVWriter class will help you to understand whats going on there.

**Comment by VJ-Vicky** [comment]
Hey, Thanks for the link and information about the files. I have checked the files but couldn't understand how should I manipulate `byte[] data` so that I could create video which I desire. 

Can you please provide me any help or could forward me to the right person to whom I should be asking this question. I have already bought Red5Pro server licence. Now My app is getting delayed because of this only.

Hope you understand and looking forward for a positive response :)

Thank You

Regards,
Vishwajeet

**Comment by mondain** [comment]
Theres a red5pro blog post or document that details the h264/avc video bytes; if I can find it, I'll direct you to it.

**Comment by VJ-Vicky** [comment]
Hello Paul,

Good Morning. I have gone through the blog post to which you provided the link. But there is this issue Andy haven't explained how to actually inject something in a stream. He has just showed how we analyze a video file and all the packets that are there in a video.

I think he was going to explain injecting video in part 2 of the blog which he hadn't posted yet and its been a while since he posted part 1. So, can you please forward me to him so that I may discuss this issue with him?

Thank You.

Regards
Vishwajeet Srivastava

**Comment by mondain** [comment]
Andy mentioned to me yesterday that he would like to post part two; I don't know what the timeline on it is though. I can in the interim point you to a demo app I did which doesn't combine streams, but it does allow switching between streams that then publish to a single stream; its analogous to what a TV station does with switching between cameras. Maybe it will help with your task
https://github.com/mondain/sandbox/tree/master/redsupport339

**Comment by VJ-Vicky** [comment]
Thanks for the link :D :+1:  . May I ask will I be able to record the outgoing stream as just 1 whole video?

**Comment by mondain** [comment]
You'd have to turn on recording, but yes, that can work.

**Comment by VJ-Vicky** [comment]
Thanks a lot. Paul I will try this and surely let you know very soon :D :+1: :100:

**Comment by VJ-Vicky** [comment]
Hello Paul,

Good Morning. I have tried to use the example that you provided us, but it is not fit to resolve my issue I need to know how to add data dynamically into a stream. I will have to wait for Andy's second blog post.

Hope Andy finishes up the 2nd part and post it very soon, my whole app is getting delayed due to this.
