### ISSUE TITLE
Error: Could not find or load main class org.red5.server.Bootstrap in eclipse

### ISSUE THREAD

**Issue by BigB0ss** [Red5/red5-server#207]
# Issue

### Short description
i can not start the server in the eclipse

console

Starting Red5
Error: Could not find or load main class org.red5.server.Bootstrap
Java HotSpot(TM) 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
### Environment

[] Operating system and version: windows 7 x64
[] Java version: 1.8.0_101
[] Red5 version:1.0.7RELEASE

### Steps to reproduce
1. red5 plugin was installed
2. red5 server runtime was created
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
Make sure the red5 plugin is pointing at the correct red5 jar files; I know this can be tricky, but there are tutorials out there to walk you through it. Here is a pro specific one that might help https://www.red5pro.com/docs/server/eclipsesetup/
