### ISSUE TITLE
can't start service

### ISSUE THREAD

**Issue by fochy** [Red5/red5-server#208]
# Issue
### Short description

can't start service
### Environment

[] Operating system and version:  windows 7 x64
[] Java version: java 8u111
[] Red5 version: 1.0.8-M11
### Expected behavior

**Put as much detail here as possible**
### Actual behavior

C:\Program Files (x86)\Red5>red5.bat
Starting Red5
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this releas
e.
Java HotSpot(TM) Client VM warning: Using the ParNew young collector with the Se
rial old collector is deprecated and will likely be removed in a future release
Error: Could not find or load main class Files
### Steps to reproduce
1. C:\Program Files (x86)\Red5>red5.bat
2. ...
3. no profit

fixed:
red5 installation path was too long
### Logs

**Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here**

**Comment by mondain** [comment]
So `fixed` is the fix that worked for you?

**Comment by thphan75** [comment]
mondain, I think that's what he meant, I just got the same issue and when I uninstalled and reinstalled it in say C:\Red5 it worked.

**Comment by alallier** [comment]
Confirmed that this solution worked for me. I had to install in the `c` base directory

**Comment by mondain** [comment]
Service startup depends upon the path; this is not our doing, it is based on Apache's use of procrun.

**Comment by khoir335** [comment]
> mondain, I think that's what he meant, I just got the same issue and when I uninstalled and reinstalled it in say C:\Red5 it worked.

thank you this works
