### ISSUE TITLE
ubuntu 16.04 apt-get install red5-server error

### ISSUE THREAD

**Issue by noamtahan** [Red5/red5-server#209]
# Issue

### Short description
When trying to install red5 server with apt-get I get an error.

### Environment

[] Operating system and version: ubuntu 16.04 LTS
[] Java version: 1.8.0_111
[] Red5 version: apt-get version

### Expected behavior
install finfsh successfully.

### Actual behavior
Failed to start LSB: Red5.
Unit enterde failed state.

### Steps to reproduce
1. sudo su
2. apt-get update
3. apt-get install red5-server
4. apt-get install -f red5-server

**Comment by mondain** [comment]
We dont support nor maintain the deb which is installable in that manner; use a tarball on the releases page https://github.com/Red5/red5-server/releases
