### ISSUE TITLE
Error: Call to a possibly undefined method getProperty through a reference with static type flash.net:SharedObject.

### ISSUE THREAD

**Issue by john1726** [Red5/red5-server#210]
# Issue

### Short description
__Brief description of what happened__

When I attempt to build my BigBlueButton application that is using Red5 by adding a SharedObject according to https://github.com/Red5/red5-server/wiki/Shared-Objects, I get the above error.  Could you please tell me, why can it not find this function?  I thought it was part  of ActionScript SharedObject: see https://helpx.adobe.com/adobe-media-server/ssaslr/sharedobject-class.html

```
                          private var so:SharedObject;

                        private function myFunc():void {
                           // ...
                           var map = so.getProperty("attributeMap");
                           // ...
                       }
```

### Environment

[] Operating system and version: Ubuntu 14.04 64-biBt
[] Java version: java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-0ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
[] Red5 version: The most up-to-date version that bigbluebutton is using at the time of this post, 1.0.6

### Expected behavior
__Put as much detail here as possible__
I expected the *.mxml file to build in the bigbluebutton-client directory and allow me to retrieve the "attributeMap" property from that shared object.

### Actual behavior
Here is part of my build output:
```
    [mxmlc] Loading configuration file /home/rmoore/dev/tools/apache-flex-sdk-4.13.0-bin/frameworks/flex-config.xml
    [mxmlc] /home/rmoore/dev/bigbluebutton/bigbluebutton-client/src/org/bigbluebutton/modules/timer/views/TimerWindow.mxml(224):  Error: Call to a possibly undefined method getProperty through a reference with static type flash.net:SharedObject.
    [mxmlc] 
    [mxmlc]                             var map = so.getProperty("attributeMap");
    [mxmlc] 

BUILD FAILED
/home/rmoore/dev/bigbluebutton/bigbluebutton-client/build.xml:201: The following error occurred while executing this line:
/home/rmoore/dev/bigbluebutton/bigbluebutton-client/build.xml:373: mxmlc task failed
```

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
I don't see any AS3 code instantiating the `so` nor connecting it to the server; if thats not there, add it.

**Comment by john1726** [comment]
I'm guessing the version of ActionScript that the BigBlueButton team used doesn't have that API.  Here is an example of their use of shared objects: https://github.com/bigbluebutton/bigbluebutton/blob/v0.81-release/bigbluebutton-client/src/org/bigbluebutton/main/model/users/UsersSOService.as
