### ISSUE TITLE
help red5 

### ISSUE THREAD

**Issue by markusgraj** [Red5/red5-server#215]
Hi of who will help me install red5 on Ubuntu 14.04, I can not to this to deal
 thank Marek

**Comment by promax204** [comment]
first you've gonna need java install java 
#apt-get install default-jre

you can download red5 and extract using 
# tar -xzf <tarfile>
[https://github.com/Red5/red5-server/releases](url) 

then cd red5 folder then run it ./red5.sh

**Comment by markusgraj** [comment]
hi if you help me to do it?? because I do not work


________________________________
Od: jemuel de la victoria <notifications@github.com>
Wysłane: 18 grudnia 2016 21:39
Do: Red5/red5-server
DW: markusgraj; Author
Temat: Re: [Red5/red5-server] help red5 (#215)


first you've gonna need java install java
#apt-get install default-jre

you can download red5 and extract using

tar -xzf

https://github.com/Red5/red5-server/releases<url>

then cd red5 folder then run it ./red5.sh

-

**Comment by ashleyconnor** [comment]
What error do you get?
