### ISSUE TITLE
No login details on admin panel

### ISSUE THREAD

**Issue by radiohit** [Red5/red5-server#217]
# I cannot acces the admin panel of red5.
   Since i have no information about how to get the username and or password
   http://localhost:5080/demos/adminPanel.html

### Environment

[] Operating system and version:Centos 6.0
[] Java version:The latest version
[] Red5 version:red5-server-1.0.8-RELEASE.tar.gz

### Expected behavior
Login details

### Actual behavior
No login details

### Steps to reproduce
None

### Logs
We dont have any logs

**Comment by mondain** [comment]
I cant find the info on this; I think its `admin` and `password` but IDK. Feel free to modify the db or code to add your own users.
