### ISSUE TITLE
ProtocolException: Error during decoding  for Object parameter '{}'

### ISSUE THREAD

**Issue by mdevries121** [Red5/red5-server#223]
# Issue
Red5 1.0.8 fails to decode an AMF0 NetConnection  call invoke with a single parameter of new Object() passed.

### Short description
I was attempting to upgrade from red5 1.0.7 to 1.0.8 but was having disconnections shortly after my client application connected to Red5 with an RTMPProtocolDecoder error present in the logs.  Converting the hex buffer to ASCII and following the decoder stack trace showed that the buffer underflows when attempting to decode the properties which are expected to be present in a simple Object parameter.  An empty object appears to cause the underflow due to having no properties.

### Environment

[] Operating system and version:  
[] Java version: Java(TM) SE Runtime Environment (build 1.8.0_92-b14)  
[] Red5 version: 1.0.8 RELEASE  

### Expected behavior
Service call invocation with an empty Object.

### Actual behavior
ProtocolException occurs and the connection is closed.  See log file below.

### Steps to reproduce
    nc = new NetConnection();
    nc.objectEncoding = flash.net.ObjectEncoding.AMF0;
    nc.connect("rtmp://SOMEURI/SCOPE");
    nc.call("notes.requestNotesHistory", null, new Object());

### Workaround
As the empty objects were not necessary for my call structure, I simply caught and removed them before performing the .call().  My application began to work as it had in 1.0.7 at that point.

### Logs
http://pastebin.com/emT48YD0

**Comment by mondain** [comment]
`Buffer.hasRemaining()` is now checked before processing, this should catch any empty objects. The fix will be in the next push.
