### ISSUE TITLE
where to get red5 [video whisper wp plugin files]

### ISSUE THREAD

**Issue by arvindpundir7** [Red5/red5-server#229]
# Issue

### Short description
__where i can get red5 [video whisper wp plugin files for video chat]__

### Environment

[] Operating system and version:
[] Java version:
[] Red5 version:

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
We have no ties to whisper; I'm not even sure what that is.
