### ISSUE TITLE
red5 1.0.8  jdk 1.8 tomcat 8.0.4 devel system windows 64 wind StandardContext.startInternal

### ISSUE THREAD

**Issue by 13539956066** [Red5/red5-server#235]
#Software development environment
red5 1.0.8
jdk 1.8
tomcat 8.0.4
system windows7 64

#ERROR　:

[RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
[RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors

Flash Builder connect red5
#ERROR　:
[WARN] [NioProcessor-2] org.red5.io.object.Deserializer - Black list is not yet
initialized
[WARN] [RTMPConnectionExecutor-1] org.red5.server.net.rtmp.RTMPHandler - Scope n
ot found
org.red5.server.exception.ScopeNotFoundException: Scope not found: example in nu

**Comment by 13539956066** [comment]
INTELLIJ IDEA  
# maven
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.demo</groupId>
  <artifactId>example</artifactId>
  <packaging>war</packaging>
  <version>1.0.8-SNAPSHOT</version>
  <name>example</name>
  <url>http://maven.apache.org</url>
  <properties>
    <jdk.version>1.8</jdk.version>
    <red5.version>1.0.8-RELEASE</red5.version>
    <red5.server>D:/javaObj/example/red5-server.jar</red5.server>
    <red5.server.io>D:/javaObj/example/red5-io-1.0.8-RELEASE.jar</red5.server.io>
    <red5.server.common>D:/javaObj/example/red5-server-common-1.0.8-RELEASE.jar</red5.server.common>
    <spring.version>4.3.5.RELEASE</spring.version>
    <spring-security.version>4.3.5.RELEASE</spring-security.version>
    <nls-service-sdk>D:/javaObj/example/nls-service-sdk.jar</nls-service-sdk>
    <opencv-sdk>D:/javaObj/example/opencv-320.jar</opencv-sdk>
    <slf4j.version>1.7.22</slf4j.version>
    <logback.version>1.1.7</logback.version>
    <mina.version>2.0.8</mina.version>
    <junit.version>4.12</junit.version>
    <commons.lang3.version>3.3.2</commons.lang3.version>
    <commons.dbcp2.version>2.1</commons.dbcp2.version>
    <mybatis.version>3.2.3</mybatis.version>
    <mybatis.spring.version>1.2.2</mybatis.spring.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${slf4j.version}</version>
      </dependency>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.hamcrest</groupId>
        <artifactId>hamcrest-junit</artifactId>
        <version>2.0.0.0</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-junit</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jul-to-slf4j</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>log4j-over-slf4j</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-access</artifactId>
      <version>${logback.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-core</artifactId>
      <version>${logback.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>${logback.version}</version>
    </dependency>
    <dependency>
      <groupId>cglib</groupId>
      <artifactId>cglib-nodep</artifactId>
      <version>2.2.2</version>
    </dependency>
    <dependency>
      <groupId>org.red5</groupId>
      <artifactId>red5-server</artifactId>
      <version>${red5.version}</version>
      <scope>system</scope>
      <systemPath>${red5.server}</systemPath>
    </dependency>
    <dependency>
      <groupId>org.red5</groupId>
      <artifactId>red5-io</artifactId>
      <version>${red5.version}</version>
      <scope>system</scope>
      <systemPath>${red5.server.io}</systemPath>
    </dependency>
    <dependency>
      <groupId>org.red5</groupId>
      <artifactId>red5-server-common</artifactId>
      <version>${red5.version}</version>
      <scope>system</scope>
      <systemPath>${red5.server.common}</systemPath>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-beans</artifactId>
      <version>${spring.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context-support</artifactId>
      <version>${spring.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${spring.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>${spring.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-expression</artifactId>
      <version>${spring.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-aop</artifactId>
      <version>${spring.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <version>${spring.version}</version>
    </dependency>
    
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <version>${spring.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty</artifactId>
      <version>3.7.0.Final</version>
    </dependency>

    <dependency>
      <groupId>nls-service</groupId>
      <artifactId>nls-service-sdk</artifactId>
      <version>1.0</version>
      <scope>system</scope>
      <systemPath>${nls-service-sdk}</systemPath>
    </dependency>

    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.3.1</version>
    </dependency>

    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>servlet-api</artifactId>
      <version>2.5</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${commons.lang3.version}</version>
    </dependency>

    <dependency>
      <groupId>org.codehaus.jackson</groupId>
      <artifactId>jackson-mapper-asl</artifactId>
      <version>1.8.8</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-dbcp2</artifactId>
      <version>${commons.dbcp2.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
      <version>2.3</version>
    </dependency>
    <dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis</artifactId>
      <version>${mybatis.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis-spring</artifactId>
      <version>${mybatis.spring.version}</version>
    </dependency>

    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>stringtemplate</artifactId>
      <version>4.0.2</version>
    </dependency>
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>5.1.35</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>opencv</artifactId>
      <version>3.1.0-1.3</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacv</artifactId>
      <version>1.3.3</version>
    </dependency>
  </dependencies>
  <build>
    <finalName>example</finalName>
    <plugins>
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-eclipse-plugin</artifactId>
        <version>2.9</version>
        <configuration>
          
          <downloadSources>true</downloadSources>
          <downloadJavadocs>false</downloadJavadocs>
          
          <wtpversion>2.0</wtpversion>
        </configuration>
      </plugin>
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <source>${jdk.version}</source>
          <target>${jdk.version}</target>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <packagingExcludes>WEB-INF/lib/*.jar</packagingExcludes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.18.1</version>
        <configuration>
          <skipTests>false</skipTests>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

# red5-web.xml
<?xml version="1.0" encoding="UTF-8" ?>
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns:lang="http://www.springframework.org/schema/lang"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/lang http://www.springframework.org/schema/lang/spring-lang.xsd">

	<bean id="placeholderConfig" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="location" value="/WEB-INF/red5-web.properties" />
	</bean>
	<bean id="web.context" class="org.red5.server.Context" autowire="byType" />
	<bean id="web.scope" class="org.red5.server.scope.WebScope" init-method="register">
		<property name="server" ref="red5.server" />
		<property name="parent" ref="global.scope" />
		<property name="context" ref="web.context" />
		<property name="handler" ref="web.handler" />
		<property name="contextPath" value="${webapp.contextPath}" />
		<property name="virtualHosts" value="${webapp.virtualHosts}" />
	</bean>
	<bean id="web.handler" class="com.demo.Application" />
</beans>
# web.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<web-app
        xmlns="http://java.sun.com/xml/ns/j2ee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
        version="2.4">

  <display-name>example</display-name>

  <context-param>
    <param-name>webAppRootKey</param-name>
    <param-value>/example</param-value>
  </context-param>

  <listener>
    <listener-class>org.red5.logging.ContextLoggingListener</listener-class>
  </listener>
  <filter>
    <filter-name>LoggerContextFilter</filter-name>
    <filter-class>org.red5.logging.LoggerContextFilter</filter-class>
  </filter>

  <filter-mapping>
    <filter-name>LoggerContextFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>

  <servlet>
    <servlet-name>gateway</servlet-name>
    <servlet-class>
      org.red5.server.net.servlet.AMFGatewayServlet
    </servlet-class>
    <load-on-startup>1</load-on-startup>
  </servlet>

  <servlet-mapping>
    <servlet-name>gateway</servlet-name>
    <url-pattern>/gateway</url-pattern>
  </servlet-mapping>

  <security-constraint>
    <web-resource-collection>
      <web-resource-name>Forbidden</web-resource-name>
      <url-pattern>/streams/*</url-pattern>
    </web-resource-collection>
    <auth-constraint/>
  </security-constraint>

</web-app>

**Comment by mondain** [comment]
Update to the latest release or milestone; versions prior to 1.0.9 have be superseded.

**Comment by 13539956066** [comment]
Hello! I've already updated to the 1.0.9 version, and the flash Builder connection is still going wrong
[WARN] [NioProcessor-2] org.red5.server.net.rtmp.RTMPHandler - Scope not found
org.red5.server.exception.ScopeNotFoundException: Scope not found: example in null


red5-web.xml
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns:lang="http://www.springframework.org/schema/lang"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/lang http://www.springframework.org/schema/lang/spring-lang.xsd">

	<bean id="placeholderConfig" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="locations">
			<list>
				<value>/WEB-INF/red5-web.properties</value>
				<value>classpath:mybatis.properties</value>
			</list>
		</property>
	</bean>
	
	<bean id="web.context" class="org.red5.server.Context" autowire="byType" />
	
	<bean id="web.scope" class="org.red5.server.scope.WebScope">
		<property name="server" ref="red5.server" />
		<property name="parent" ref="global.scope" />
		<property name="context" ref="web.context" />
		<property name="handler" ref="web.handler" />
		<property name="contextPath" value="${webapp.contextPath}" />
		<property name="virtualHosts" value="${webapp.virtualHosts}" />
	</bean>
	
	
	<bean id="web.handler" class="com.video.Application" />
	<import resource="classpath:spring-bean.xml" />
	
</beans>

# com.video.Application
import java.util.*;
import org.red5.server.adapter.ApplicationAdapter;
import org.red5.server.api.IConnection;
import org.red5.server.api.scope.IScope;
import org.red5.server.api.stream.IServerStream;

public class Application extends ApplicationAdapter {

    private IScope appScope;

    private IServerStream serverStream;

    /** {@inheritDoc} */
    @Override
    public boolean appStart(IScope app) {
        super.appStart(app);
        log.info("oflaDemo appStart");
        System.out.println("oflaDemo appStart");
        appScope = app;
        return true;
    }

    /** {@inheritDoc} */
    @Override
    public boolean appConnect(IConnection conn, Object[] params) {
        log.info("oflaDemo appConnect");


        return super.appConnect(conn, params);
    }

    /** {@inheritDoc} */
    @Override
    public void appDisconnect(IConnection conn) {
        log.info("oflaDemo appDisconnect");
        if (appScope == conn.getScope() && serverStream != null) {
            serverStream.close();
        }
        super.appDisconnect(conn);
    }
}

There is a problem, very feel back

**Comment by mondain** [comment]
Scope not found means you dont have the scope you requested or it failed to start. I suggest turning up your logger to see where or how it may have failed to start up. Ensure that you are not using a Spring context loader in your web.xml.

**Comment by 13539956066** [comment]
Thank you for your reply. It was when I loaded mybatis-3 that there was a problem
