### ISSUE TITLE
org.red5.net.websocket.codec.WebSocketDecoder - Handshake failed

### ISSUE THREAD

**Issue by bhawin-bigstep** [Red5/red5-server#236]
i am getting this error when i try to start Broadcast on my local Machine 
http://localhost:5080/live/broadcast.jsp

I have installed all the modules listed here

https://stackoverflow.com/questions/41202595/red5-pro-unexpected-response-code-400-websocketexception-handshake-failed#

Still it doesn't work

I am using Ubuntu 14.04
My red5pro version is 3.5

**Comment by mondain** [comment]
The WebRTC broadcast will not work without a valid Red5 Pro license key. The websocket failing to connect is an indicator.
