### ISSUE TITLE
Unrecognized VM option 'MaxMetaspaceSize=128m

### ISSUE THREAD

**Issue by dh3wr** [Red5/red5-server#240]
# Issue

### Short description
Not starting due to ``Unrecognized VM option 'MaxMetaspaceSize=128m'``

### Environment

[] Operating system and version: debian 64 bit
[] Java version: OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-2~deb8u1)
[] Red5 version: 1.0.10 Milestone 4

### Expected behavior
server should start

### Actual behavior
./red5.sh fails with message
````
root@videostream:/usr/share/red5# ./red5.sh
Running on  Linux
Starting Red5
Unrecognized VM option 'MaxMetaspaceSize=128m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
````

### Steps to reproduce
1. Install debian
2. Follow the instuctions on https://github.com/Red5/red5-server/wiki/Installation-on-Linux
3. Install java with ``apt-get install openjdk-7-jre``
4. Start the server with ./red5.sh

**Comment by dh3wr** [comment]
Works with Oracle JDK 8 from https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-debian-8

**Comment by mondain** [comment]
Java 7 is beyond is support lifetime from Oracle; if any user is not on Java 8, they should immediately upgrade.
