### ISSUE TITLE
intercept streams

### ISSUE THREAD

**Issue by wuhj666** [Red5/red5-server#243]
What should I do if I want to intercept streams.

**Comment by mondain** [comment]
Write a plugin or app to intercept them.

**Comment by wuhj666** [comment]
@Override
	public void streamBroadcastStart(IBroadcastStream stream) {
		// TODO Auto-generated method stub
		super.streamBroadcastStart(stream);
		stream.addStreamListener(new IStreamListener() {
			@Override
			public void packetReceived(IBroadcastStream arg0, IStreamPacket arg1) {
				// TODO Auto-generated method stub
				byte[] receve_data = arg1.getData().array();
			}
		});
	}


Define a class extends MultiThreadedApplicationAdapter and override any method with a parameter 
 IBroadcastStream.
