### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by dukkh4** [Red5/red5-server#245]
# Issue
Proceeded to install accordnig to wiki doccumentation found here https://github.com/Red5/red5-server/wiki/Installation-on-Linux but when i run ./red5.sh & server times out

### Short description
get these error message;

[INFO] [pool-7-thread-1] org.red5.server.service.ShutdownServer - One or more contexts didn't close in the allotted time
[INFO] [Thread-5] org.red5.server.service.ShutdownServer - One or more contexts didn't close in the allotted time

### Environment

[] Operating system and version: Centos 7
[] Java version: openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
[] Red5 version: red5-server-1.0.10-M4

### Expected behavior
server to start normally

### Actual behavior
server crash on contexts

### Steps to reproduce
1. cd /usr/share/red5
2. ./red5.sh &

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by zhangzhentao** [comment]
I've had this problem too. Have you solved it?

**Comment by dukkh4** [comment]
Not yet. still waiting on feedback from red5 team

**Comment by FabianJimenezEsparza** [comment]
1. Declara la variable RED5_HOME
2. Checa que tengas el puerto habilitado con iptables o firewall
3. nmap localhost

**Comment by dukkh4** [comment]
variable is RED5_HOME=/usr/share/red5 just like they show in tutorial.

ports sem to be opened. Here is my nmap results;

Starting Nmap 6.40 ( http://nmap.org ) at 2018-01-08 07:21 EST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000080s latency).
Not shown: 980 closed ports
PORT      STATE SERVICE
21/tcp    open  ftp
22/tcp    open  ssh
25/tcp    open  smtp
53/tcp    open  domain
80/tcp    open  http
110/tcp   open  pop3
111/tcp   open  rpcbind
143/tcp   open  imap
443/tcp   open  https
587/tcp   open  submission
993/tcp   open  imaps
995/tcp   open  pop3s
1935/tcp  open  rtmp
2222/tcp  open  EtherNet/IP-1
3306/tcp  open  mysql
5080/tcp  open  onscreen
8081/tcp  open  blackice-icecap
9999/tcp  open  abyss
10000/tcp open  snet-sensor-mgmt
20000/tcp open  dnp

Nmap done: 1 IP address (1 host up) scanned in 0.06 second

**Comment by FabianJimenezEsparza** [comment]
Teclea 
ls -l /usr/share/red5

Estás levantando el servicio bajo la cuenta de root o de alguna otra?
Http://localhost:5080.  Que te marca?
Por lo que veo sino está levantando es que tienes algún daemon que ocupa ese puerto.

**Comment by FabianJimenezEsparza** [comment]
Teclea 
telnet localhost 5080

**Comment by dukkh4** [comment]
No, nothing uses  port 5080 when performing ls -l /usr/share/red5

SO i will check if another daemon is using the port.

**Comment by mondain** [comment]
Test running the red5 server without any apps/plugins you've installed/created to exclude them as the source of the issue. If that doesn't produce a running server, up the log levels for red5 core and paste a log to pastebin for review.

**Comment by deeprathod** [comment]
Facing the same issue. Couldn't find any solution in the current thread. 

`org.red5.server.service.ShutdownServer - One or more contexts didn't close in the allotted time`

 Please Help !!

**Comment by mondain** [comment]
@deeprathod same test applies https://github.com/Red5/red5-server/issues/245#issuecomment-356308266

**Comment by deeprathod** [comment]
Thank you for your reply @mondain I am using aws ec2  with the new instance, not sure exactly, by meaning `Test running the red5 server without any apps/plugins you've installed/created to exclude them as the source of the issue.` Currently i just have apache installed on this, do you mean it should be clean instance ?

**Comment by mondain** [comment]
What OS? What JDK? You need JDK 8 or newer based on which Red5 tarball you download.

**Comment by deeprathod** [comment]
Hi @mondain  Below is the configuration 

Java Version `openjdk version "1.8.0_242"`
OS `NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="xxx:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"`
