### ISSUE TITLE
ofla demo streaming videos not playing

### ISSUE THREAD

**Issue by Shazrina1994** [Red5/red5-server#247]
I am new to RED5 and I wanted to test the  oflademo in classic version. afterall the configurations the streaming video not playing and as the error says "description = Connection failed: Application folder ([install-location]/applications/oflaDemo) is missing."
please help me to go ahead.

**Comment by mondain** [comment]
The folder you've pasted isn't used by the demo; place your files in `webapps/oflaDemo/streams` and they will show in the listing.
