### ISSUE TITLE
Red5-WrapperTest

### ISSUE THREAD

**Issue by ederdedeus** [Red5/red5-server#251]
Good morning I was using Red5 on a Windows 7 server, and it worked perfectly, but I had to change Server that is also a windows 7, and now this is giving this problem it is not loading. You are using it with the lightIRC.

Thanks for any kind of help.

Thank you.

Windows 7
jre1.8.0_171
Red5 Server 1.0.1

Invocation of init method failed; nested exception is java.net.BindException: <-- Wrapper Stopped

Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
NOT STARTED.

Exception org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'red5.core' defined in class path resource [red5.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.FileSystemXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rtmpTransport' defined in class path resource [red5-core.xml]: Invocation of init method failed; nested exception is java.net.BindException: Cannot assign requested address: bind

https://pastebin.com/i2eanLCe
https://pastebin.com/4MT0zB7p

# Issue

### Short description
__Brief description of what happened__

### Environment

[] Operating system and version:
[] Java version:
[] Red5 version:

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
`Cannot assign requested address: bind` that usually means something else bound to your IP and / or port; sort that out and you're good to go.
