### ISSUE TITLE
How to run Red5 Server in Eclipse?

### ISSUE THREAD

**Issue by biiyamn** [Red5/red5-server#253]
I've checkout the source code of red5 server (red5-server, red5-io,red5-service) , How to run red5 in eclipse.

**Comment by mondain** [comment]
Run the server using the red5-debug.bat or red5-debug.sh and connect the Eclipse debugger, or use https://github.com/Red5/red5-eclipse-plugin (which isn't being maintained).

**Comment by biiyamn** [comment]
Thank you mondain, but i need to start server from source code (standalone ) , is it possible?  like StandAlone.class in older red5 version

**Comment by mondain** [comment]
A means to do that in the old way is not provided; you'd be on your own there.
