### ISSUE TITLE
When I pushed the stream to red5 server,Why has been reconnected the red5 server on my Android phone with AnyRTC

### ISSUE THREAD

**Issue by knightjie99** [Red5/red5-server#254]
# Issue
When I pushed the stream to red5 server on my  Android phone .After a few seconds ,the live begin reconnected agin and agin.
### Short description
__Brief description of what happened__
When I pushed the stream to red5 server,Why has been reconnected the red5 server on my Android phone with AnyRTC

### Environment

[] Operating system and version:Linux version 3.10.0-693.11.6.el7.x86_64  (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )

[] Java version:java 8

[] Red5 version: 1.0.10 Milestone 6

### Expected behavior
connected is ok,the live is ok

### Actual behavior
reconnected agin and agin

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
Red5 does not support AnyRTC; I believe you are trying something unsupported or you've not been clear as to what is wrong.
