### ISSUE TITLE
How to send object to client?

### ISSUE THREAD

**Issue by ddsgdsg** [Red5/red5-server#255]
For example, I want to send to client this object
```
{
     "users": {
           "username": "test"
    }
}
```
how can I do this?
Sorry for asking here I don't believe anyone would reply to me on StackOverflow.

**Comment by mondain** [comment]
A SharedObject or any custom method should work.

**Comment by ddsgdsg** [comment]
I want to send it via return but I do not get how to send such object. Passing it directly to return doesn't work.

**Comment by mondain** [comment]
There are many ways to pass data back and forth with a flash/rtmp server; you need to decide which one you want to use. Here are several googled answers:
 * https://stackoverflow.com/questions/1565088/how-can-i-send-messages-from-red5-to-my-flash-as3-app
 * https://flexnflex.wordpress.com/2009/04/19/sending-data-from-flex-to-a-javaserver-page/

One of our own demo applications here using WebSockets: https://github.com/Red5/red5-websocket-chat
