### ISSUE TITLE
Trying to connect to war location Issue

### ISSUE THREAD

**Issue by zunair-syed** [Red5/red5-server#259]
# Issue
Installed on RHEL as instructed, but going to the installer page, I'm faced with the error:
"trying to connect to war location
Netstatus: NetConnection.Connect.Failed"

### Short description
This happens for almost all demos. Cannot run any of the demos

### Environment

[] Operating system and version: Red hat Enterprise
[] Java version: 1.8
[] Red5 version: Latest Release (stable)

### Expected behavior
Shud have seen the demos

**Comment by zunair-syed** [comment]
@mondain I read some of your threads on this issue, and tried my best, but could not resolve it.

**Comment by mondain** [comment]
The installer.swf is pretty much dead; if you want a war demo, drop it in the `webapps` directory and let the war loader pick it up and deploy when it processes the folder at interval.
