### ISSUE TITLE
Installer.swf has no contents

### ISSUE THREAD

**Issue by RashmiC091427** [Red5/red5-server#261]
# Issue
The installer.swf in /webapps/installer/ has no files in it when opened.

### Short description
__Brief description of what happened__
1.Downloaded red5 server
2.Downloaded Flash player
3.started red5 server with double click on red5.bat file.
4.Launched http://localhost:5080
5.Image on page stating red5 could be seen.
6.On trying to open isntaller.swf , empty file is getting opened.
![red5_server_issue](https://user-images.githubusercontent.com/45000107/48407347-9c4b7b00-e75c-11e8-9e83-7e00ef4897cc.JPG)

### Environment

[] Operating system and version:Windows 7
[] Java version: 1.8.0
[] Red5 version:1.0.6

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
I'm not supporting any of the swf code any longer; its all available in the public repos, if others want to use it.
