### ISSUE TITLE
Bundle with Java Version for Windows Enviorments

### ISSUE THREAD

**Issue by JPVenson** [Red5/red5-server#267]
# Issue
You should bundle a Java Version within an single executable to ease deployment and use on a Windows system that does not have java installed
### Short description
I want to install Red5 on a Windows server that does not have Java installed as a System wide feature. To prevent someone from installing a 3rd party software other then Red5 you should bundle Java with Red5 and ship this single executable instead. This allows users to download a single executable.

### Environment

[] Operating system and version: Windows Server 2016
[] Java version: X
[] Red5 version: Each

### Expected behavior
There is only one executable that can be executed without java installed.

### Actual behavior
You have to install java and set a system wide Environment Variable

**Comment by mondain** [comment]
While it would be a convenience to a small percentage of users to include a JVM, it will most likely not be happening. There is an installer project here which anyone may use to provide this support https://github.com/Red5/installer
