### ISSUE TITLE
org.red5.server.scheduling.JDKSchedulingService cannot be found

### ISSUE THREAD

**Issue by JoKr9527** [Red5/red5-server#272]
# Issue
As the title describes, I cannot get this class. I'm using version 1.1.1

**Comment by mondain** [comment]
This would be due to mismatched or missing jars for the version 1.1.1 series; ensure that you've got all the red5 1.1.1 jars and only 1.1.1. For io, commons, etc

**Comment by folousiot** [comment]
Have you solved it? This is my errors, all in /red5-server-master/src/main/java/org/red5/server/adapter/MultiThreadedApplicationAdapter.java
as folows:

Description	Resource	Path	Location	Type
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 962	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 979	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 997	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1015	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1028	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1041	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1054	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1066	Java Problem
The import org.red5.server.scheduling cannot be resolved	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 71	Java Problem

**Comment by mondain** [comment]
I've added the missing package in `red5-server-common`. Somehow it was not included in the last push, my mistake. https://github.com/Red5/red5-server-common/tree/master/src/main/java/org/red5/server/scheduling

**Comment by JoKr9527** [comment]
thank you .
