### ISSUE TITLE
I am a novice. How to integrate Red5 1.1.1 into Tomcat8.5

### ISSUE THREAD

**Issue by zgy00123** [Red5/red5-server#274]
# Issue

### Short description
__Brief description of what happened__

### Environment

[] Operating system and version:
[] Java version:
[] Red5 version:

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
We don't support the "war" version of Red5 anymore; if you wanted this mode of operation, you'd have to do the development work based on our older implementation.

**Comment by zgy00123** [comment]
Thanks




------------------ 原始邮件 ------------------
发件人: "Paul Gregoire"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 晚上10:38
收件人: "Red5/red5-server"<red5-server@noreply.github.com>;
抄送: "Brilliance"<26133573@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Red5/red5-server] I am a novice. How to integrate Red5 1.1.1into Tomcat8.5 (#274)




We don't support the "war" version of Red5 anymore; if you wanted this mode of operation, you'd have to do the development work based on our older implementation.
