### ISSUE TITLE
Flash Player required for demos

### ISSUE THREAD

**Issue by Sturmey66** [Red5/red5-server#280]
# Issue
Flash player is required for demos.

### Short description
Unable to launch demo without flashplayer.

### Environment

[] Operating system and version: Windows 10 Pro
[] Java version: latest
[] Red5 version: latest

### Expected behavior
HTML 5.0 not flash.

### Actual behavior
Flash is required to view demos.
Documentation for demos is also suspect, but Flash?

### Steps to reproduce
1. Install Java
2. set java_home
3. install and run Red5
4. discover you can't access anything because of legacy software requirements and need to install flash
5. try to enter an issue in GitHub

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

? uhm, I don't know what logs you need

NOTE: I'm not a programmer. I'm the guy who helps users get programs to run. This looks promising, but the open source project has an incredibly steep learning curve to get off the ground.

**Comment by mondain** [comment]
We're working on alternatives, see #276 #283
