### ISSUE TITLE
1.2.2 maven 无法使用

### ISSUE THREAD

**Issue by Lance201314** [Red5/red5-server#281]
# Issue

**Comment by mondain** [comment]
Please keep the queries to English; I have to use google translate to get an idea of what you want and make an assumption. Red5 Server 1.2.2 is not available on maven central, but 1.2.3 is and fixes an issue or two.

**Comment by mondain** [comment]
Also, the releases may be found here as well: https://github.com/Red5/red5-server/releases (1.2.2 is there)
