### ISSUE TITLE
How to config Red5-sever cluster?

### ISSUE THREAD

**Issue by jj11332906** [Red5/red5-server#285]
# Issue
How to config Red5-sever cluster?
### Short description
I need config red5-server cluster in linux server.

### Environment

[] Operating system and version:linux centOs
[] Java version:jdk1.8
[] Red5 version:red5-server-1.0.10-M5

hello
      please give me completely config steps,Thanks!

**Comment by mondain** [comment]
Red5 server (open source) does not built-in clustering enabled. If you need clustered Red5 instances, you'll have to use something like [Red5 Pro Server](https://red5pro.com/).

**Comment by jj11332906** [comment]
thanks reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paul Gregoire"<notifications@github.com&gt;; 
发送时间: 2019年11月23日(星期六) 凌晨0:16
收件人: "Red5/red5-server"<red5-server@noreply.github.com&gt;; 
抄送: "11332906"<11332906@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Red5/red5-server] How to config Red5-sever cluster? (#285)




Red5 server (open source) does not built-in clustering enabled. If you need clustered Red5 instances, you'll have to use something like Red5 Pro Server.
