### ISSUE TITLE
pom.xml Error...  (org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain)

### ISSUE THREAD

**Issue by coolcjg** [Red5/red5-server#286]
# Issue
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain (execution: default, phase: validate)	

### Short description
1.New install
2. Maven update
3.pom.xml error happens!!!

### Environment
[] Operating system and version: windows
[] Java version:1.8
[] Red5 version: 
        <groupId>org.red5</groupId>
        <artifactId>red5-parent</artifactId>
        <version>1.2.3</version>

Help me.....

**Comment by solomax** [comment]
this seems to be Eclipse specific error
you can ignore it

**Comment by mondain** [comment]
Yes, use Quick fix -> Ignore
