### ISSUE TITLE
Installation fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by mdalepiane** [Red5/red5-server#29]
This issue is already reported here:
https://bugs.launchpad.net/ubuntu/+source/red5/+bug/1312814

**Quoting the report:**
To reproduce: ubuntu 14.04 LTS

```
sudo apt-get install red5-server
"red5-server: Depends: libtomcat6-java (>= 6.0.20-7) but it is not going to be installed"
```

then:

`sudo apt-get install libtomcat6-java`

This successfully brings in all dependencies for libtomcat6-java and installs.
Trying again after manually meeting the libtomcat6-java dependency:

```
sudo apt-get install red5-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libred5-java
The following NEW packages will be installed:
  libred5-java red5-server
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,023 kB of archives.
After this operation, 1,372 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package libred5-java.
(Reading database ... 263596 files and directories currently installed.)
Preparing to unpack .../libred5-java_1.0~svn4374-3_all.deb ...
Unpacking libred5-java (1.0~svn4374-3) ...
Selecting previously unselected package red5-server.
Preparing to unpack .../red5-server_1.0~svn4374-3_all.deb ...
Unpacking red5-server (1.0~svn4374-3) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libred5-java (1.0~svn4374-3) ...
Setting up red5-server (1.0~svn4374-3) ...
Allowing use of questionable username.
Adding system user `_red5' (UID 119) ...
Adding new user `_red5' (UID 119) with group `nogroup' ...
Not creating home directory `/usr/share/red5'.
 * Starting Flash streaming server red5-server [fail]
invoke-rc.d: initscript red5-server, action "start" failed.
dpkg: error processing package red5-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 red5-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Take22** [comment]
omg is there any solution?

**Comment by mondain** [comment]
Yes, the solution is to use the tarball

**Comment by paleozogt** [comment]
+1

**Comment by manaman19** [comment]
Hi.  Can you expound upon the solution "use the tarball?"  I am aware of what a tarball is, but I am not familiar with the process that I would use to install using one or even where to find the tarball of this package.  Any details, links, etc. that you could provide would be helpful.  Thus far my linux software installation experience is limited to the graphical interface and apt-get.  Thanks in advance even if it's just the location of the tarball, I'm sure I can look up the rest.

**Comment by solomax** [comment]
1) Go to the releases page: https://github.com/Red5/red5-server/releases
2) download tarball: https://github.com/Red5/red5-server/releases/download/v1.0.5-RELEASE/red5-server-1.0.5-RELEASE-server.tar.gz (or you can use *.zip)
3) extract it somewhere
4) run red5.sh (red5.bat)

**Comment by coderawal** [comment]
@solomax I'm using tarball for installation and ran red5.sh command but the console is stuck at 
"[INFO] [Launcher:/chat] org.red5.server.scope.WebScope - Webscope already registered" whats the problem can't figure it out.

**Comment by solomax** [comment]
Do you have any issues during connecting the server?

**Comment by coderawal** [comment]
No issues at all, have tried several times but stucks at same place.

**Comment by solomax** [comment]
What do you mean by stuck?
Are you able to connect your server? (in browser http://localhost:5080)

**Comment by coderawal** [comment]
the server is not being installed (ubuntu 14.04), not connecting to "http://localhost:5080", and stuck(halt) means the problem i stated in my first comment, my web terminal halts in message stated in first comment.

**Comment by solomax** [comment]
you have started the script on the server
after that you should be able to connect to the server using your browser

**Comment by pankajsingh210** [comment]
Hey @coderawal -  it stucks because "webscope" is already registered, and the code is trying to register it again. So you need to comment "webscope" block from the given xml file. I had faced the same issue. Suppose if you are stuck at "[ Launcher / chat ]" then you need to edit file at 
    usr/share/red5/webapps/chat/WEB-INF/red5-web.xml
comment the code containing "webscope".

**Comment by badbob2046** [comment]
Why is ubuntu so shit?
