### ISSUE TITLE
Error installing on CentOS 8

### ISSUE THREAD

**Issue by fvlasie** [Red5/red5-server#293]
# Issue

### Short description
Output:
```Running on  Linux
Starting Red5
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Error: Could not find or load main class org.red5.server.Bootstrap
Caused by: java.lang.ClassNotFoundException: org.red5.server.Bootstrap
```

### Environment

[] Operating system and version: CentOS 8
[] Java version: JDK 14
[] Red5 version: 1.2.3

### Expected behavior
It should run.

### Actual behavior
Spits out error as above.

### Steps to reproduce
1. Follow instructions on Wiki https://github.com/Red5/red5-server/wiki/Installation-on-Linux
2. Launch with ./red5.sh

TIA

**Comment by mondain** [comment]
The current 1.2.x versions are built for JDK 11

**Comment by mondain** [comment]
Up-to JDK 17 the server has been run in several installs; all that must be done, is to adjust the startup scripts as indicated by the JVM. The one above is just a notification of an upcoming change, not an error. Removing `-Xverify:none` and `-noverify` easily makes it go away.
