### ISSUE TITLE
build.xml

### ISSUE THREAD

**Issue by davorgit** [Red5/red5-server#3]
it would be nice to have build.xml in trunk for building ROOT.war

**Comment by otagtekin** [comment]
Is there anyway for red5 team to create step by step guide to create target from the red-server trunk. Older versions this wasn't an issue however the same run configurations do not work for the new version since the bootstrap files are moved a separate location.

**Comment by mondain** [comment]
Here's the sequence that I use: red5-io, red5-server-common, red5-client, red5-service, and red5-server

**Comment by otagtekin** [comment]
Did you merge all the files into one big application? Thank you.
