### ISSUE TITLE
red5 server native dependencies

### ISSUE THREAD

**Issue by debjitk** [Red5/red5-server#308]
Is red5 server pure `java` or it has dependencies on `native libraries` ?

**Comment by solomax** [comment]
it is written in java only

**Comment by debjitk** [comment]
@solomax What i wanted to know is the have any `native dependencies` like `libavcodec` etc. If it is pure Java how does it transcode live stream ?

**Comment by solomax** [comment]
AFAIK Red5 doesn't perform any transcoding
You can check it with `mvn dependency:tree` :)

**Comment by mondain** [comment]
As Max replied, there is currently no transcoding in the open source core Red5 codebase; no native code whatsoever, it is all java.
