### ISSUE TITLE
Unrecognized VM option 'UseZGC'

### ISSUE THREAD

**Issue by mominet2** [Red5/red5-server#318]
Run red5.bat：
Starting Red5
Unrecognized VM option 'UseZGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Environment：
[] Operating system and version: Windows 10
[] Java version: 1.8.0_201
[] Red5 version: 1.2.8

**Comment by lfengo** [comment]
同上一样错误提示，windows2008r2sp1

**Comment by mominet2** [comment]
> 同上一样错误提示，windows2008r2sp1

这玩意不行，问题太多了，解决一个还有下一个，文档还特别少，已经换成SRS了。

**Comment by mominet2** [comment]
JDK8根本就不支持UseZGC这个选项，去掉就可以，但是还有其他各种问题等着你去解决。诸多问题表明这个东西根本就没有进行完整的测试。

**Comment by supersam-web** [comment]
same problem here!

**Comment by dlutsunmingze** [comment]
咋整？

**Comment by chushiyun2015** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mondain** [comment]
The ZGC garbage collector is not available on all platforms using Java 11; if a platform does not have ZGC, simply remove it from the start script options.
