### ISSUE TITLE
can't running test with Junit and maven

### ISSUE THREAD

**Issue by Rouxhero** [Red5/red5-server#319]
# Issue

### Short description

Hi, we are working on your project for a computer science class.  We need to run the tests with  maven and use them on sonarQube. 
But when we want to run tests, we re getting an issue:

### Environment

[] Operating system and version: Windows 10 with WSL 1 ubuntu 20.04.3 
[] Java version:
```
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
[] Red5 version:
red5-server-1.2.12

### Expected behavior
Get tests

### Actual behavior
```
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ red5-server ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
``` 

### Steps to reproduce
1.  mvn clean
2.  mvn test

### Logs

https://pastebin.com/E9QENVfw

**Comment by chushiyun2015** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mondain** [comment]
Run `mvn test -Dmaven.test.skip=false` instead; the default per our pom is to skip tests.
