### ISSUE TITLE
打包后运行

### ISSUE THREAD

**Issue by ssdutlong** [Red5/red5-server#320]
![image](https://user-images.githubusercontent.com/39684461/158329615-908c9cea-4a25-475a-83f5-b7ab2d4a08f4.png)![Uploading image.png…]()
mvn -Dmaven.test.skip=true install后，执行java -jar red5-server-1.2.2.jar报错

**Comment by mondain** [comment]
The `red5-server-common.jar` has to be in your classpath as that is where Red5.class is located.

**Comment by chushiyun2015** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
