### ISSUE TITLE
This is question for use red5. It’s not issues

### ISSUE THREAD

**Issue by nanxia990105** [Red5/red5-server#326]
# Issue

### Short description
__Brief description of what happened__
I use Pom dependency down success, but I don’t know how to use it like spring? Please tell me red5 has like Middleware’s Working with documents

**Comment by mondain** [comment]
@nanxia990105 I don't understand your question. Red5 uses Spring to configure itself, that's the gist.

**Comment by Ikenna0001** [comment]
http://{my.ip.address}:5080/installer not working why?

**Comment by mondain** [comment]
@Ikenna0001 because Adobe killed flash player, the installer uses a swf which requires flash player.

**Comment by chushiyun2015** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
