### ISSUE TITLE
Error upon starting the server

### ISSUE THREAD

**Issue by rurilaam** [Red5/red5-server#331]
Anyone can help checking why there's error?

![B](https://user-images.githubusercontent.com/113960600/191166672-89e8dc07-fab1-41bf-b3c6-4f20aec1659d.JPG)
![A](https://user-images.githubusercontent.com/113960600/191166640-79b392d3-8a08-4e9d-9816-07924d14c9e1.JPG)

**Comment by beetlejesss** [comment]
Do you get an error if you just run `./red5.sh` directly?

**Comment by umeshshende** [comment]
This issue #332 may resolve your problem.
