### ISSUE TITLE
"The JAVA_HOME environment variable is not defined correctly"

### ISSUE THREAD

**Issue by adammpolak** [Red5/red5-server#337]
# Issue

### Short description
When trying to run `install-service.bat` this appears: 

```red5-server>install-service.bat
Processor Architecture: "AMD64"
Using Daemon:           "C:\Users\adamm\dev\red5-server\\amd64\prunsrv.exe"
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

### Environment

[] Operating system and version: Windows 11
[] Java version: 19
[] Red5 version: 1.3.12

### Expected behavior
Should be able to run the installer

**Comment by mondain** [comment]
@adammpolak your JAVA_HOME should be defined in the system / os where the service launch can access it.

**Comment by adammpolak** [comment]
> @adammpolak your JAVA_HOME should be defined in the system / os where the service launch can access it.

I was able to echo that it was set, yet the issue still occurs :(

**Comment by Sadoharu** [comment]
![image](https://github.com/Red5/red5-server/assets/77967977/57d09fbc-5555-49d7-9fe9-e5f7dd0e04a6)

....

**Comment by chushiyun2015** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huguangjun580** [comment]
是jdk版本的问题吗

**Comment by mondain** [comment]
I believe there are more than enough tutorials to be found showing how to set up environmental variables on every operating system where the JDK can execute. Belaboring it here is a bit more than I want to support.
