### ISSUE TITLE
Video not streaming

### ISSUE THREAD

**Issue by cbhutad** [Red5/red5-server#344]
# Issue

### Short description
We are using red5 server to play videos for our website. The server allows downloading for files but does not stream.

### Environment

[] Operating system and version: CentOs 7.0
[] Java version: 11 OpenJdk
[] Red5 version: 1.3.25

### Expected behavior
Should allow the streaming for video files. The file format is m3u8 file

### Actual behavior
When the link for the video is accessed then it asks for adobe flash player to be downloaded.

### Steps to reproduce
1. Setup the server
2. Added the video file in webapps/vod/streams folder
3. Ran the server

**Comment by mondain** [comment]
To stream hls (m3u8/ts) you'll need an webapp or plugin that provides HLS, the default server does not stream it by default.
