### ISSUE TITLE
add Host Name Alias for red 5

### ISSUE THREAD

**Issue by noamtahan** [Red5/red5-server#35]
Hey,
I am trying to change the ip address to domain name.
I understood that red5 run on apache tomcat so, what is the right way to change that to domain name.
How to add a Host Name Alias? What is and where is the config file to add the aliases?
The main Idea is that I want to get access to play movie not with ip address but domain name
Thanks

**Comment by oryfoxer7410** [comment]
I'm wondering the same. How to change from IP to url. Your assistance would be appreciated.

**Comment by mondain** [comment]
If you two are talking about Tomcat Virtual Hosts, you'll have to implement that feature yourselves or just hook into whatever is available already in Tomcat.
