### ISSUE TITLE
oflademo.war(r4797) can't be installed

### ISSUE THREAD

**Issue by mdchemlab** [Red5/red5-server#44]
I had installed red 1.0.3 yesterday,but I can't install the oflademo.war(r4797),
The error is ：
 The application version selected does not match the server java version,

admin-r4506-java6.war and SOSample-r4326-java6.war can be installed.
SystemUtils-1.0-r4418.war can't be installed.

I had installed oflaDemo-r4472-java6.war several days ago, it's ok. 
My server had installed java-1.7.0-openjdk jre-7u45-linux-x64 jdk-8u25-linux-x64 .
Anybody can give suggestions?

**Comment by romanown** [comment]
The requested URL /svn/snapshots/oflaDemo.war was not found on this server.

**Comment by mondain** [comment]
Look at issue #180
