### ISSUE TITLE
Update demos with RTSP usage

### ISSUE THREAD

**Issue by supercharger** [Red5/red5-server#45]
I don't see the RTSP usage in the demo, Can you please update it.
Android doesn't support RTMP, so this information will help alot.

I tried to stream to "rtsp://localhost/oflaDemo"  ( transmute to RTMP using restreamer or Xuggler), but the RTSP client is not even able to stream. 

Also, https://github.com/Red5/red5-server/blob/792d48b246550ce040aa7a2bddf2420295e9ba59/src/main/server/conf/red5.properties doesn't list RTSP

**Comment by mondain** [comment]
Red5 does not support RTSP natively, it must be added via plugin or another application.

**Comment by supercharger** [comment]
Is there such a existing plugin  ?
I see some code related to Axis-Camera

**Comment by mondain** [comment]
This is the only RTSP plugin that we have currently https://github.com/Red5/red5-rtsp-restreamer

**Comment by supercharger** [comment]
It would be helpful, if the project is updated with setup and usage instructions.

**Comment by mondain** [comment]
Agreed, but it was not supplied by the donor and I have not used it personally.

**Comment by sufishah2008** [comment]
Hi dear,

I am trying to merge my IP cam RTSP string with java code but getting some issue there, please help me resolve such issue.

MY IP Cam RTSP - 

rtsp://<ip>:<port>/unicast/c<channel number>/s<stream type>/live

<channel number>: 1-n<stream type>: 0(main stream) or 1(sub stream)

How may i modify your string for my IP cam

Your Code- rtsp://myserver/axis-media/media.amp?fps=15 RTSP/1.0\r\n" + "CSeq: " + nextSeq() + "\r\n" + "User-Agent: Axis AMC\r\n" + "Accept: application/sdp\r\n" + "\r\n").getBytes()
