### ISSUE TITLE
ShareObject: no sync event on client after attribute changed if value is of type Object

### ISSUE THREAD

**Issue by nusofthq** [Red5/red5-server#46]
If the value sent in setAttribute is of type Object the sync is triggered only the first time. 
After that if one of the fields of the object is modified, the object is seen as being unmodified and no sync event is triggered.

I can also track this issue down starting with Red5 1.0.1

**Comment by mondain** [comment]
This should be resolved with the commit on [red5-server-common](https://github.com/Red5/red5-server-common/commit/d01f833f446a00ccdae9b8e541db2a094d59db01) The addition of setDirty(boolean) is meant to be used to indicate a modification made to a custom object and force an update. The simple addition of "equals" will not work and modifications directly on the referenced object do not trigger a "property" change so the object appears to be unmodified to the server. So in summary, make sure you call setDirty(true) before you call setAttribute when you've modified the SharedObject attribute directly on the server; your updated example code may be found here: https://github.com/Red5/red5-issues/blob/master/src/main/java/org/red5/issues/issue46/Application.java
