### ISSUE TITLE
Where‘s the edge and origin  xml file？

### ISSUE THREAD

**Issue by orchard2012** [Red5/red5-server#48]
Where‘s the edge and origin  xml file?
Them can’t find in  '/conf'.
My Red5-server  version is  1.0.4.
**File List**
red5-edge.xml, red5-edge-core.xml
red5-origin.xml, red5-origin-core.xml

**Comment by mondain** [comment]
Clustering is not integrated in the current server; this is why you don't see those files. The original implementation has been moved to a plugin here: https://github.com/Red5/red5-plugins/tree/master/cluster
