### ISSUE TITLE
How to setup RED5 clustering and manager it 

### ISSUE THREAD

**Issue by wmz7year** [Red5/red5-server#51]
I found this document ,But it does't work in 1.0.4.

http://red5.googlecode.com/svn/doc/tags/0_8_0/HOWTO-Clustering.txt

How can I do this?

**Comment by mondain** [comment]
The old clustering is not supported in the later versions; to use it, you'd have to implement it on your own. The original creator / maintainer left the project and is not available. We have plans to support clustering in the future, but there is no time frame at this time.

**Comment by wmz7year** [comment]
@mondain Does there are relevant plans or something, I think if I can then make a contribution to RED5

**Comment by mondain** [comment]
Not sure what you mean, are you asking about custom development / professional services?

**Comment by wmz7year** [comment]
I'm not good at English,I want to participate in the development RED5.

**Comment by mondain** [comment]
Ok, no problem. New contributors start by submitting patches or pull requests.
