### ISSUE TITLE
Impossible use red5 on win7 64bits

### ISSUE THREAD

**Issue by gaelson** [Red5/red5-server#56]
Hello,
After install red5 1.0.5; I can't find service to start and impossible to connect to red 5 and install some sample.
Any issues

**Comment by mondain** [comment]
The "service" portion of red5 is found here: https://github.com/Red5/red5-service 
Also, I suggest attempting to start Red5 via the links on the start menu.

**Comment by gaelson** [comment]
Hello,
I install the red  with windows internet server. Will I use only Apache?

best regards

2015-02-13 14:26 GMT+00:00 Paul Gregoire <notifications@github.com>:

> The "service" portion of red5 is found here:
> https://github.com/Red5/red5-service
> Also, I suggest attempting to start Red5 via the links on the start menu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Red5/red5-server/issues/56#issuecomment-74260782>.
>



-- 
*Gaël ADELA*

*"**La logique vous conduira d'un point A à un point B. L'imagination et
l'audace vous conduiront où vous le désirez*.*" *
*Albert Einstein*

**Comment by mondain** [comment]
That question doesn't make sense to me; I think you may not understand what
red5 provides.

**Comment by gaelson** [comment]
Hello,

Sorry about all,
I use Red5 0.9 befor on Win7 to make live streaming.
I try the same process of installation to use the Red5 1.0.5 to build my
streaming server but nothing happing. may be I don't how to use it. Please
if you have some tutorials, provide them to me.

Thank you very much.


2015-02-13 20:19 GMT+00:00 Paul Gregoire <notifications@github.com>:

> That question doesn't make sense to me; I think you may not understand what
> red5 provides.
>
> On Fri, Feb 13, 2015, 12:41 gaelson <notifications@github.com> wrote:
>
> > Hello,
> > I install the red with windows internet server. Will I use only Apache?
> >
> > best regards
> >
> > 2015-02-13 14:26 GMT+00:00 Paul Gregoire <notifications@github.com>:
> >
> > > The "service" portion of red5 is found here:
> > > https://github.com/Red5/red5-service
> > > Also, I suggest attempting to start Red5 via the links on the start
> menu.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Red5/red5-server/issues/56#issuecomment-74260782>.
> > >
> >
> >
> >
> > --
> > *Gaël ADELA*
> >
> > *"**La logique vous conduira d'un point A à un point B. L'imagination et
> > l'audace vous conduiront où vous le désirez*.*" *
> > *Albert Einstein*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Red5/red5-server/issues/56#issuecomment-74293909>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Red5/red5-server/issues/56#issuecomment-74319925>.
>



-- 
*Gaël ADELA*

*"**La logique vous conduira d'un point A à un point B. L'imagination et
l'audace vous conduiront où vous le désirez*.*" *
*Albert Einstein*

**Comment by mondain** [comment]
My best advice is that you turn up the log level and then google any errors that show in the log. Most if not all of the errors you'd see will be in the [old wiki](https://code.google.com/p/red5/w/list) or the [new wiki](https://github.com/Red5/red5-server/wiki)
