### ISSUE TITLE
migration from 0.9

### ISSUE THREAD

**Issue by honzabrecka** [Red5/red5-server#57]
Hi,

I'm trying to migrate existing app build on Red5 < 1.0. Everything is similar, but `IContext` in current version do not contain `getResource` method. How can I get to the file of saved .flv stream?

Thanks

**Comment by mondain** [comment]
To get your flv files, use a IStreamFilenameGenerator implementation; you can see how to it here: https://github.com/Red5/red5-server/blob/master/src/main/java/org/red5/server/stream/ProviderService.java#L192

**Comment by honzabrecka** [comment]
OK, thank you. Currently I'm able to get the file, but when I try to upload it to another server (or do just GET request), I get the SocketException - permission denied. Can you give me any advice, please?
