### ISSUE TITLE
Poor video performance

### ISSUE THREAD

**Issue by pol2095** [Red5/red5-server#58]
Hello,

I install red5 on my server centos 6, and I have poor video performance, the videos are choppy.

what are the server requirements ?

Thanks

**Comment by tharldvs1** [comment]
how much ram you got, Processor?

**Comment by tharldvs1** [comment]
also what is your bandwidth?

**Comment by pol2095** [comment]
it's a small server

CPU                Cores/Threads    Freq.            RAM     Disk         Network	
Atom N2800    2c / 4t                  1.86 GHz+    2 Go    500 Go    100 Mbps

**Comment by mondain** [comment]
Poor video performance is normally due to the lack of bandwith or processing power on the broadcast end. Try testing on a local network and compare your result.

**Comment by mondain** [comment]
For the record, I've run Red5 on one of my Atom based netbooks and it worked just fine for local streams;  IMHO using an Atom processor in a server is probably not a good idea.
