### ISSUE TITLE
Red5 can't work in proper on Ubunt

### ISSUE THREAD

**Issue by pgnanasekar** [Red5/red5-server#59]
I had to install Red5 server in Ubuntu server 14.04. Web console is working. But i am not seeing the test video in home page. So that i can check the debug message was 
"Host: 192.168.5.242
Trying to connect
Net status: NetConnection.Connect.Failed
Trying to connect to war location
Net status: NetConnection.Connect.Success
Net status: NetConnection.Call.Failed "
Can u any one help me to fix the issue to work in Red5

**Comment by mondain** [comment]
Check your server log for start up errors and ensure that your rtmp and http addresses are set to 0.0.0.0.

**Comment by bmurtagh** [comment]
@pgnanasekar how did you even get past the basic package install on Ubuntu 14.04? `apt-get install libtomcat6-java` then `apt-get install red5-server`. The install completes, but fails due to ehcache init.

**Comment by mondain** [comment]
I don't use the ubuntu packages; we don't have access to update them and our debian build maintainer has been gone from quite some time. I use the tarball.

**Comment by mondain** [comment]
Here's a deb file for testing purposes: https://www.dropbox.com/s/3uxov4qil4xmluk/red5-server_1.0.5_all.deb?dl=0
