### ISSUE TITLE
 Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by welshdemon** [Red5/red5-server#60]
I understand this is a  java mismatch but documentation on fixing this is very lacking/missing/out of date. What is weird is that everything was working fine recently then all of a sudden this...

Please can somebody help. 
I have removed (renamed) a few jars from the lib directory as I read this somewhere, but the error remains.

 red5-io-1.0.4-SNAPSHOT.jar.old
 red5-io-1.0.5-RELEASE.jar.old
 red5-server-common-1.0.5-RELEASE.jar.old
 slf4j-api-1.7.7.jar.old
 slf4j-api-1.7.9.jar.old

Any idea what else to try please?

**Comment by solomax** [comment]
All jars in lib folder are REQUIRED
Additionally you need to have Java7 installed

**Comment by welshdemon** [comment]
I think this is because I tried to update from 1.0 to 1.0.5.

I don't know how to upgrade from a tarball so I renamed the 1.0 folder and just installed 1.0.5. 

I have removed the 1.0.5 and put my 1.0 folder back and it is working.

**Comment by welshdemon** [comment]
Does any of this help and do I need to change the symlink to another version?

 /usr/bin/java -> /etc/alternatives/java
/etc/alternatives/java -> /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

-bash-4.1$ ls  /usr/lib/jvm
java
java-1.6.0
java-1.6.0-openjdk-1.6.0.34.x86_64
java-1.6.0-openjdk.x86_64
java-1.7.0-openjdk-1.7.0.75.x86_64
java-1.8.0-openjdk-1.8.0.25-1.b17.el6.x86_64
java-openjdk
jre
jre-1.6.0
jre-1.6.0-openjdk.x86_64
jre-1.7.0
jre-1.7.0-openjdk.x86_64
jre-1.8.0
jre-1.8.0-openjdk
jre-1.8.0-openjdk-1.8.0.25-1.b17.el6.x86_64
jre-openjdk


Thank you.

**Comment by solomax** [comment]
In case "java -version" results to java7+ you need to check scripts you are using to start red5.
To ensure java7 is set on system level you can
1) apt-get remove jdk6 jre6 (not sure about exact names)
AND/OR
2) set the correct java using update-alternatives

**Comment by tharldvs1** [comment]
Which version of red5 are you using?

Check me out! 

     On Monday, March 9, 2015 12:26 PM, welshdemon <notifications@github.com> wrote:
   

 Does any of this help and do I need to change the symlink to another version?/usr/bin/java -> /etc/alternatives/java
/etc/alternatives/java -> /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java-bash-4.1$ ls /usr/lib/jvm
java
java-1.6.0
java-1.6.0-openjdk-1.6.0.34.x86_64
java-1.6.0-openjdk.x86_64
java-1.7.0-openjdk-1.7.0.75.x86_64
java-1.8.0-openjdk-1.8.0.25-1.b17.el6.x86_64
java-openjdk
jre
jre-1.6.0
jre-1.6.0-openjdk.x86_64
jre-1.7.0
jre-1.7.0-openjdk.x86_64
jre-1.8.0
jre-1.8.0-openjdk
jre-1.8.0-openjdk-1.8.0.25-1.b17.el6.x86_64
jre-openjdkThank you.—

**Comment by tharldvs1** [comment]
Somebody correct me if I'm wrong but according to documentation for red5 it said the target java was ment to be 1.6 but ended up being 1.8, Therefor you will need 1.8 for red5 1.0.5, Now, who wants to play around on my red5pro server and help me develop the apps?

**Comment by solomax** [comment]
AFAIK, 1.8 dependency was fixed
Current requirement is 1.7 at lease it works for us as expected

**Comment by mondain** [comment]
Target version is 1.7. The corrected issue was the dependency was built with a target of 1.7, but compiled with JDK 8. Targeting 1.7 with JDK 8 fails during runtime when using some collection features. As Maxim stated, it has been fix for awhile now.

**Comment by welshdemon** [comment]
Thanks for replies.

This didn't make sense. The startup script red5.sh is loading the default java which links to 
/usr/bin/java -> /etc/alternatives/java
/etc/alternatives/java -> /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

yet after 
yum remove java-1.6.0 (I'm on centos 6)

red5 1.0.5 starts OK.

So despite java -version and the symlinks suggesting java 1.7 was in use, it would appear that having java 1.6 installed was preventing red5 running.

Hope this helps someone else some day hence posting it.

**Comment by mondain** [comment]
Thanks for posting and I would agree that increasing the knowledge base is not a bad thing.
