### ISSUE TITLE
RTMPT connections closing suddenly

### ISSUE THREAD

**Issue by jonawebb** [Red5/red5-server#78]
We're using Red5 to host a SIP server that uses either RTMPT or RTMPS to communication with Flash clients. The problem we're seeing is that the RTMPT connections get dropped when there are more than about 10 simultaneous connections. This never happens with RTMPS. Now, I understand that RTMPS is implemented differently, using code from Adobe embedded in the Flex protocol implementation, so it seems reasonable to believe that with RTMPT the server is just being overloaded and falls behind, resulting in the connections being dropped. But we're not seeing other evidence that the server is overloaded; the processor load is nowhere near one core. There's nothing in the logs, either, to indicate what is going on right up to the point that everything seems to freeze. The next thing that happens is the server starts to handle the dropped connections. (I've looked for evidence that GC was causing this; there's no GC logged around the time of the drop.) 
Any ideas what could be causing this, or where I should look to figure out what's going on?

**Comment by mondain** [comment]
Increase the log level on the rtmpt packages. The connections shouldn't be dropping unless the player or server are not responding often or fast enough most likely.

**Comment by jonawebb** [comment]
Thanks -- but it appears to be happening in the firewall, not the client or server. We're trying to figure out why, but for some reason the firewall is closing the RTMPT connection after a while. It doesn't do this with RTMPS, or with RTMPT when we run the server on our LAN.
