### ISSUE TITLE
Issue with Flash Player 17.0.0.169

### ISSUE THREAD

**Issue by tezrosolutions** [Red5/red5-server#79]
Hi, 
I am experiencing this problem, where once a stream is recorded with red5 and I try to play it, the stream plays in a fast-forward manner.

You can reproduce this issue on this link 
http://www.technogumbo.com/tutorials/Recording-Decent-Quality-Video-And-Audio-With-Flash-and-Red5/

This happens only with Flash Player 17.0.0.169, not on the older versions.

A quick help will be appreciated.

- Umair

**Comment by mondain** [comment]
Have you tested your flv on any other server, such as FMS/AMS or Wowza? If the issue also happens there, I'd say you need to post this issue on the Flash Player bug tracker.

**Comment by davidplappertvb** [comment]
This also happens to me, and the video seems to play fine with the rest.

**Comment by mondain** [comment]
Is it any flv, or is it only for an flv recorded on a red5 server?

**Comment by tezrosolutions** [comment]
This happens for every flv on every browser running the said version of Flash Player.

**Comment by tezrosolutions** [comment]
Try opening following link on flash player version 17.0.0.169 and any older versions of flash player, you will notice the issue yourself;

http://misc-items.s3.amazonaws.com/elance/sportseed/html5_video.html

**Comment by mondain** [comment]
Yes, i see that link does ff. I'm just trying to get details. Whats the relation to HTML5, or is that just what you named the page?

**Comment by tezrosolutions** [comment]
Its just the title of the page.

**Comment by mondain** [comment]
My first guess is that they are checking the User Agent response from the server and if they are, they are bastards IMHO.

**Comment by tezrosolutions** [comment]
Yeah :)

**Comment by tezrosolutions** [comment]
This issue seems fix in Adobe flash player version 17.0.0.188

**Comment by mondain** [comment]
Closing due to fix by Adobe
