### ISSUE TITLE
Is the  plugin "rtspplugin"  for rtsp?

### ISSUE THREAD

**Issue by wxwhaha** [Red5/red5-server#81]
And how to  push the stream to red5 with "ffmpeg" via the rtspplugin ?
what's the differences between "rtspplugin" and "rtsp-restreamer"?

**Comment by mondain** [comment]
From the readme for red5-rtsp-restreamer:
Example code for Red5 server which demonstrates how to stream from an RTSP source (Specifically an Axis camera) to a live Flash media stream.

The rtsp plugin is for handling broadcasting from an RTSP source; it however is not "complete" and needs work to get to a working implementation.

If you want to broadcast from ffmpeg, use the rtmp publish at this as it is supported.
