### ISSUE TITLE
127.0.0.1 VS 192.168.1.254

### ISSUE THREAD

**Issue by wxwhaha** [Red5/red5-server#82]
why 127.0.0.1:5080/  is ok, but 192.168.1.254:5080 （my IP address in the LAN）cant't be accessed.
version:1.0.3
system:fedora 14
My colleagues have also encountered this problem.

**Comment by mondain** [comment]
Check your red5-web.properties file in your app/WEB-INF director and make sure you're not specifically specifying your apps IP addresses, use "*" instead.
