### ISSUE TITLE
How to Install RED5 Server in CentOS 6

### ISSUE THREAD

**Issue by Nirjonadda** [Red5/red5-server#88]
Hello,

How to Install RED5 Server in CentOS 6.6 x86_64 with cPanel?

Thanks

**Comment by mondain** [comment]
No personal experience doing such a thing, but may I suggest that you try the steps outlined here: http://www.aryanict.com/hub/knowledgebase/289/How-to-Install-Red5-on-cPanelorWHM-CentOS-server.html
Make sure you update the jdk and red5 versions to match your target.
