### ISSUE TITLE
Missing ehcache-dep

### ISSUE THREAD

**Issue by leberknecht** [Red5/red5-server#90]
On ubuntu 14.10 x64 i get this on startup
```
Exception org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'red5.common' defined in class path resource [red5.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.FileSystemXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'statusObjectService' defined in class path resource [red5-common.xml]: Invocation of init method failed; nested exception is net.sf.ehcache.CacheException: java.lang.AssertionError: No net.sf.ehcache.EhcacheInit services found
```
Workaround from here works:
https://bugs.launchpad.net/ubuntu/+source/red5/+bug/1283218

So please put it to the deps :)

**Comment by mondain** [comment]
I don't have nor see this issue in Ubuntu, I'd rather not extra jars if its not necessary.

**Comment by b3wii** [comment]
I have the same problem. Fresh install of Ubuntu server 14.04 and then installing kaltura which worked fine but when i installed red5-server and try starting it it throws this error:

[red5-server-start.txt](https://github.com/Red5/red5-server/files/171697/red5-server-start.txt)

**Comment by solomax** [comment]
I believe *.deb installer is not supported
you can download/install tar.gz version containing all necessary dependencies
