### ISSUE TITLE
RTMPT does not work when using Red5 as part of my war with my context name ("/mywar")

### ISSUE THREAD

**Issue by ronenn** [Red5/red5-server#91]
When using Red5 version 1.0.5 as part of my own WAR, RTMPT does not work. After debugging, I saw the reason for it is that my WAR context name is not "" but "/mywar". 
In org.red5.server.net.rtmpt.RTMPTServlet class the method "setRequestInfo" parse the URI from the start, therefore shift the computed values left because part of the URI is "/mywar". Instead, if the decoding would have started from the end, there was not ant issue.

**Comment by mondain** [comment]
Are you running Red5 in another JEE container? or are you running your war in Red5? If its another container, you'll have to pipe the rtmpt requests to Red5.

**Comment by ronenn** [comment]
I am running red5 in my own war in my own tomcat. The context of the war is not ROOT. 
To overcome the rtmpt pipe, I have Apache httpd which forward requests to my war.

**Comment by mondain** [comment]
In your case, you've got to tunnel the RTMPT requests to your Red5 webapp.

**Comment by mondain** [comment]
There is a tunnel servlet for performing the routing.
