### ISSUE TITLE
Tomcat8 support

### ISSUE THREAD

**Issue by solomax** [Red5/red5-server#94]
Hello Paul,

maybe we can switch tomcat version to be 8.0.23? I can help migrating :)

**Comment by mondain** [comment]
Not sure when I'd be able to get to it the month, but if you want to take it on; I say go for it. Just create a pull request.

**Comment by solomax** [comment]
Hello Paul,

it seems I was able to add tomcat8 support
should I create PR for new branch or PR for master will be OK? (red5-plugins/tomcat and red5-server are affected)

**Comment by solomax** [comment]
have created 2 PRs for master
please let me know if anything need to be changed :)

**Comment by mondain** [comment]
Thanks a lot Max, I'll check them out later today.

**Comment by mondain** [comment]
Merged and soon to be released with 1.0.6
