### ISSUE TITLE
Some jars in 1.0.5 release are built using jdk8

### ISSUE THREAD

**Issue by solomax** [Red5/red5-server#95]
Hello Paul,

just have downloaded zip and tar.gz version of red5 1.0.5 release and check red5-server.jar file.
It's META-INF/MANIFEST.MF claims it was built using jdk8

AFAIR these artifacts were re-created to contain jars build using jdk7, could you please check if it is issue with our cache/proxy or binaries need to be fixed one more time?

**Comment by mondain** [comment]
The release may be built with jdk 8; I may have only updated the maven repo, but it was back in Feb so I'm not certain.

**Comment by mondain** [comment]
I've modified my local scripts to use jdk 7, but the next release 1.0.6 may be the last one built for jdk less than 8. All java users should be aware of the end-of-support for the jdks http://www.oracle.com/technetwork/java/eol-135779.html
