### ISSUE TITLE
Maven error

### ISSUE THREAD

**Issue by sammy-abraham** [Red5/red5-server#96]
[ERROR] Failed to execute goal on project red5-server: Could not resolve dependencies for project org.red5:red5-server:jar:1.0.5-RELEASE: Failure to find org:jaudiotagger:jar:2.0.4-SNAPSHOT in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]

I'm using eclipse on windows7 and I got this error, when I  command "Maven install". it seems  pom.xml file is not working. How can I deal with this?

**Comment by solomax** [comment]
Recent versions of jaudiotagger library are not in the Maven anymore: https://bitbucket.org/ijabz/jaudiotagger/issue/67/maven-repository-for-new-versions, not sure what can be done here :(

**Comment by sammy-abraham** [comment]
Thank you for your quick reply. There is a jaudiotagger-2.0.4-SNAPSHOT.jar file in the red5-server-1.0.2-RELEASE. 
Is it possible to make a red5-server.jar file using that? I am new to using Maven. If you know, could you teach me how?

**Comment by solomax** [comment]
https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

with latest Maven this should work: mvn install:install-file -Dfile=<path-to-file>

**Comment by sammy-abraham** [comment]
Thanks, I'll try that.

**Comment by shawkinaw** [comment]
It seems the `groupId` of jaudiotagger has changed to `net.jthink`. The artifact is available here:

https://maven.java.net/content/groups/public/net/jthink/jaudiotagger/2.0.4-SNAPSHOT/

but since it has the new `groupId` I believe the dependencies of red5-io will need to be updated, unless there's a way to alias maven dependencies that I don't know about.

This repo (see [here](https://maven2-repository.java.net)) will also need to be added to `settings.xml` to find the artifact.

**Comment by Freeeeday** [comment]
I just want to install by maven successfully. Is there any good idea?

**Comment by mondain** [comment]
The "install" target is not configured for the red5-server.

**Comment by AlejandroMoran** [comment]
Automatic builds are also failing.

https://builds.apache.org/view/M-R/view/OpenMeetings/job/Red5-server/975/console

**Comment by mondain** [comment]
Should all be back to normal now

**Comment by maxgronlund** [comment]
I'm checking out red5 chat example on os x

`[INFO] ------------------------------------------------------------------------
[INFO] Building chat 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org:jaudiotagger:jar:2.0.4-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.843 s
[INFO] Finished at: 2015-11-12T08:37:32+01:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chat: Could not resolve dependencies for project org.red5.demos:chat:war:1.0: Failure to find org:jaudiotagger:jar:2.0.4-SNAPSHOT in http://repo.m`

**Comment by solomax** [comment]
I believe we need to switch to newly available https://dl.bintray.com/ijabz/maven/net/jthink/jaudiotagger/2.2.5/:jaudiotagger-2.2.5.pom

available after adding additional repo as described here:
https://bitbucket.org/ijabz/jaudiotagger/

or help ijabz to publish to one of the centrals :)

**Comment by mondain** [comment]
Having it on sonatype or a central would be ideal, but adding the repo seems like a good workaround for the time being.

**Comment by mondain** [comment]
Fixed on last commit of red5-server-common

**Comment by maxgronlund** [comment]
? Downloaded a pristine copy this morning. and installed

**Comment by solomax** [comment]
Hello Paul,
I see no changes in the pom :(
Could you please point me to the commit reference with this change?

**Comment by solomax** [comment]
Additional question: why do you need jaudiotagger dependency? source code contain zero entries of 'jaudiotagger' word :( (both red5-server-common and red5-server)

**Comment by mondain** [comment]
MP3Reader uses it, the changes are in https://github.com/Red5/red5-io

**Comment by solomax** [comment]
red5-io I see ...
Unfortunately I currently need to strip this library due to license incompatibility :(
https://bitbucket.org/ijabz/jaudiotagger/issues/2/add-apache-license
Hopefully will be able to resolve this

**Comment by mondain** [comment]
Sorry I didn't notice the license difference. If you know of a more compatible library I'm fine with switching to it.

**Comment by solomax** [comment]
Will try to contact original authors of the library and get permission to dual licence first :)
The library is being stripped for more than 4 year, and no-one noticed that :) (seems to be not used by OM code :))
